/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_questdb_net_Epoll */

#ifndef _Included_com_questdb_net_Epoll
#define _Included_com_questdb_net_Epoll
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_questdb_net_Epoll_epollCreate
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_questdb_net_Epoll_epollCtl
        (JNIEnv *, jclass, jlong, jint, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_questdb_net_Epoll_epollWait
        (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     com_questdb_net_Epoll
 * Method:    getDataOffset
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_questdb_net_Epoll_getDataOffset
        (JNIEnv *, jclass);

/*
 * Class:     com_questdb_net_Epoll
 * Method:    getEventsOffset
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_questdb_net_Epoll_getEventsOffset
        (JNIEnv *, jclass);

JNIEXPORT jshort JNICALL Java_com_questdb_net_Epoll_getEventSize
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_questdb_net_Epoll_getEPOLLIN
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_questdb_net_Epoll_getEPOLLET
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_questdb_net_Epoll_getEPOLLOUT
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_questdb_net_Epoll_getEPOLLONESHOT
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_questdb_net_Epoll_getCtlAdd
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
