/*+*****************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.griffin;

import io.questdb.griffin.engine.functions.array.ArrayCreateFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayAvgFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayCountFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayCumSumFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayElemAvgFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayElemMaxFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayElemMinFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayElemSumFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayFlattenFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayInsertionPointAfterEqualFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayInsertionPointFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayMaxFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayMinFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayPositionFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayReverseFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayRoundFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayShiftDefaultNaNFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayShiftFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArraySortDescFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArraySortFullFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArraySortFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayStdDevFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayStdDevPopFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayStdDevSampFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArraySumFunctionFactory;
import io.questdb.griffin.engine.functions.array.DoubleArrayTransposeFunctionFactory;
import io.questdb.griffin.engine.functions.array.IntIntervalFunctionFactory;
import io.questdb.griffin.engine.functions.array.IntIntervalRightOpenFunctionFactory;
import io.questdb.griffin.engine.functions.bool.AndFunctionFactory;
import io.questdb.griffin.engine.functions.bool.BetweenTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.bool.InDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.bool.InLongFunctionFactory;
import io.questdb.griffin.engine.functions.bool.InStrFunctionFactory;
import io.questdb.griffin.engine.functions.bool.InSymbolFunctionFactory;
import io.questdb.griffin.engine.functions.bool.InTimestampTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.bool.InVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.bool.NotFunctionFactory;
import io.questdb.griffin.engine.functions.bool.OrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastBooleanToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastByteToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastCharToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDateToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastDoubleToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastFloatToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastGeoHashToGeoHashFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastGeoHashToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastGeoHashToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIPv4ToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIPv4ToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIPv4ToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToIPv4FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastIntToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToSymbolFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLong256ToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToGeoHashFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastLongToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastNullTypeFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastShortToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToGeoHashFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToIPv4FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToUuidFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastStrToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastSymbolToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastTimestampToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastUuidToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastUuidToVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToBooleanFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToByteFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToCharFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToDateFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToFloatFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToGeoHashFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToIPv4FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToIntFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToLong256FunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToLongFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToShortFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToStrFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.cast.CastVarcharToUuidFunctionFactory;
import io.questdb.griffin.engine.functions.conditional.CaseFunctionFactory;
import io.questdb.griffin.engine.functions.conditional.NullIfDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.conditional.NullIfIntFunctionFactory;
import io.questdb.griffin.engine.functions.conditional.NullIfLongFunctionFactory;
import io.questdb.griffin.engine.functions.conditional.NullIfStrFunctionFactory;
import io.questdb.griffin.engine.functions.conditional.NullIfVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.conditional.SwitchFunctionFactory;
import io.questdb.griffin.engine.functions.date.AddLongToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.date.DateTruncFunctionFactory;
import io.questdb.griffin.engine.functions.date.DayOfMonthFunctionFactory;
import io.questdb.griffin.engine.functions.date.DayOfWeekFunctionFactory;
import io.questdb.griffin.engine.functions.date.DayOfWeekSundayFirstFunctionFactory;
import io.questdb.griffin.engine.functions.date.DaysPerMonthFunctionFactory;
import io.questdb.griffin.engine.functions.date.ExtractFromTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.date.HourOfDayFunctionFactory;
import io.questdb.griffin.engine.functions.date.IsEndOfMonthFunctionFactory;
import io.questdb.griffin.engine.functions.date.IsLeapYearFunctionFactory;
import io.questdb.griffin.engine.functions.date.MicrosOfMillsFunctionFactory;
import io.questdb.griffin.engine.functions.date.MillisOfSecondFunctionFactory;
import io.questdb.griffin.engine.functions.date.MinuteOfHourFunctionFactory;
import io.questdb.griffin.engine.functions.date.MonthOfYearFunctionFactory;
import io.questdb.griffin.engine.functions.date.NanosOfMicrosFunctionFactory;
import io.questdb.griffin.engine.functions.date.SecondOfMinuteFunctionFactory;
import io.questdb.griffin.engine.functions.date.TimestampAddFunctionFactory;
import io.questdb.griffin.engine.functions.date.TimestampCeilFunctionFactory;
import io.questdb.griffin.engine.functions.date.TimestampDiffFunctionFactory;
import io.questdb.griffin.engine.functions.date.TimestampFloorFromFunctionFactory;
import io.questdb.griffin.engine.functions.date.TimestampFloorFromOffsetUtcFunctionFactory;
import io.questdb.griffin.engine.functions.date.TimestampFloorFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToDateFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToNanoTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToNanoTimestampVCFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToStrDateFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToStrTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToTimestampVCFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToTimezoneTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.date.ToUTCTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.date.WeekOfYearFunctionFactory;
import io.questdb.griffin.engine.functions.date.YearFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqCharCharFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqDateFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqDoubleArrayFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqIPv4FunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqIPv4StrFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqIntFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqIntStrCFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqLong256FunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqLong256StrFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqLongFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqStrCharFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqStrFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqSymCharFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqSymFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqSymLongFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqSymStrFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqSymTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqUuidFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqUuidStrFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.eq.EqVarcharStrFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtCharFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtDateFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtDoubleVVFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtIntFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtLongFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtStrFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtStrVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.lt.LtVarcharStrFunctionFactory;
import io.questdb.griffin.engine.functions.math.AbsDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.AbsIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.AbsLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.AbsShortFunctionFactory;
import io.questdb.griffin.engine.functions.math.AcosDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.AddDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.AddFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.AddIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.AddLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.AsinDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.Atan2DoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.AtanDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseAndIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseAndLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseNotIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseNotLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseOrIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseOrLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseXorIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.BitwiseXorLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.CeilDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.CeilFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.CeilingDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.CeilingFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.CosDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.CotDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.DegreesDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.DivDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.DivFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.DivIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.DivLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.ExpDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.FloorDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.FloorFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.LnDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.LogDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.MulDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.MulFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.MulIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.MulLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.NegByteFunctionFactory;
import io.questdb.griffin.engine.functions.math.NegDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.NegFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.NegIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.NegLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.NegShortFunctionFactory;
import io.questdb.griffin.engine.functions.math.PIDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.PowDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.RadiansDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.RemDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.RemFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.RemIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.RemLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.RoundDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.RoundDoubleZeroScaleFunctionFactory;
import io.questdb.griffin.engine.functions.math.RoundDownDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.RoundHalfEvenDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.RoundUpDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.SignByteFunctionFactory;
import io.questdb.griffin.engine.functions.math.SignDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.SignFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.SignIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.SignLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.SignShortFunctionFactory;
import io.questdb.griffin.engine.functions.math.SinDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.SqrtDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.SubDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.math.SubFloatFunctionFactory;
import io.questdb.griffin.engine.functions.math.SubIntFunctionFactory;
import io.questdb.griffin.engine.functions.math.SubLongFunctionFactory;
import io.questdb.griffin.engine.functions.math.SubTimestampFunctionFactory;
import io.questdb.griffin.engine.functions.math.TanDoubleFunctionFactory;
import io.questdb.griffin.engine.functions.regex.ILikeStrFunctionFactory;
import io.questdb.griffin.engine.functions.regex.ILikeSymbolFunctionFactory;
import io.questdb.griffin.engine.functions.regex.ILikeVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.regex.LikeStrFunctionFactory;
import io.questdb.griffin.engine.functions.regex.LikeSymbolFunctionFactory;
import io.questdb.griffin.engine.functions.regex.LikeVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.ConcatFunctionFactory;
import io.questdb.griffin.engine.functions.str.LTrimStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.LTrimVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.LeftStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.LeftVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.LengthBytesVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.LengthStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.LengthSymbolFunctionFactory;
import io.questdb.griffin.engine.functions.str.LengthVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.LowerFunctionFactory;
import io.questdb.griffin.engine.functions.str.LowerVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.PositionFunctionFactory;
import io.questdb.griffin.engine.functions.str.PositionVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.RTrimStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.RTrimVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.ReplaceStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.ReplaceVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.RightStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.RightVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.StartsWithStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.StartsWithVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.StrPosFunctionFactory;
import io.questdb.griffin.engine.functions.str.StrPosVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.SubStringFunctionFactory;
import io.questdb.griffin.engine.functions.str.SubStringVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.ToLowercaseFunctionFactory;
import io.questdb.griffin.engine.functions.str.ToLowercaseVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.ToUppercaseFunctionFactory;
import io.questdb.griffin.engine.functions.str.ToUppercaseVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.TrimStrFunctionFactory;
import io.questdb.griffin.engine.functions.str.TrimVarcharFunctionFactory;
import io.questdb.griffin.engine.functions.str.UpperFunctionFactory;
import io.questdb.griffin.engine.functions.str.UpperVarcharFunctionFactory;
import io.questdb.std.ObjHashSet;

/**
 * The audited scalar function factories whose construction depends only on their typed arguments: a private leaf
 * may relocate before adoption and a selected call may be constructed again. A factory qualifies by its exact class;
 * the cache's argument-swapping and negating aliases inherit the flag from their source descriptor.
 */
final class RelocatableScalarFactories {
    private static final ObjHashSet<Class<? extends FunctionFactory>> FACTORIES = new ObjHashSet<>();

    private RelocatableScalarFactories() {
    }

    static boolean contains(FunctionFactory factory) {
        return FACTORIES.contains(factory.getClass());
    }

    static {
        FACTORIES.add(AddDoubleFunctionFactory.class);
        FACTORIES.add(AddFloatFunctionFactory.class);
        FACTORIES.add(AddIntFunctionFactory.class);
        FACTORIES.add(AddLongFunctionFactory.class);
        FACTORIES.add(AbsShortFunctionFactory.class);
        FACTORIES.add(AbsIntFunctionFactory.class);
        FACTORIES.add(AbsLongFunctionFactory.class);
        FACTORIES.add(AbsDoubleFunctionFactory.class);
        FACTORIES.add(AcosDoubleFunctionFactory.class);
        FACTORIES.add(AsinDoubleFunctionFactory.class);
        FACTORIES.add(Atan2DoubleFunctionFactory.class);
        FACTORIES.add(AtanDoubleFunctionFactory.class);
        FACTORIES.add(CeilDoubleFunctionFactory.class);
        FACTORIES.add(CeilFloatFunctionFactory.class);
        FACTORIES.add(CeilingDoubleFunctionFactory.class);
        FACTORIES.add(CeilingFloatFunctionFactory.class);
        FACTORIES.add(CosDoubleFunctionFactory.class);
        FACTORIES.add(CotDoubleFunctionFactory.class);
        FACTORIES.add(DegreesDoubleFunctionFactory.class);
        FACTORIES.add(ExpDoubleFunctionFactory.class);
        FACTORIES.add(FloorDoubleFunctionFactory.class);
        FACTORIES.add(FloorFloatFunctionFactory.class);
        FACTORIES.add(LnDoubleFunctionFactory.class);
        FACTORIES.add(LogDoubleFunctionFactory.class);
        FACTORIES.add(PIDoubleFunctionFactory.class);
        FACTORIES.add(PowDoubleFunctionFactory.class);
        FACTORIES.add(RadiansDoubleFunctionFactory.class);
        FACTORIES.add(RemDoubleFunctionFactory.class);
        FACTORIES.add(RemFloatFunctionFactory.class);
        FACTORIES.add(RemIntFunctionFactory.class);
        FACTORIES.add(RemLongFunctionFactory.class);
        FACTORIES.add(RoundDoubleZeroScaleFunctionFactory.class);
        FACTORIES.add(RoundDoubleFunctionFactory.class);
        FACTORIES.add(RoundDownDoubleFunctionFactory.class);
        FACTORIES.add(RoundUpDoubleFunctionFactory.class);
        FACTORIES.add(RoundHalfEvenDoubleFunctionFactory.class);
        FACTORIES.add(SignByteFunctionFactory.class);
        FACTORIES.add(SignDoubleFunctionFactory.class);
        FACTORIES.add(SignFloatFunctionFactory.class);
        FACTORIES.add(SignIntFunctionFactory.class);
        FACTORIES.add(SignLongFunctionFactory.class);
        FACTORIES.add(SignShortFunctionFactory.class);
        FACTORIES.add(SinDoubleFunctionFactory.class);
        FACTORIES.add(SqrtDoubleFunctionFactory.class);
        FACTORIES.add(TanDoubleFunctionFactory.class);
        FACTORIES.add(NegByteFunctionFactory.class);
        FACTORIES.add(NegShortFunctionFactory.class);
        FACTORIES.add(AddLongToTimestampFunctionFactory.class);
        FACTORIES.add(DateTruncFunctionFactory.class);
        FACTORIES.add(DayOfMonthFunctionFactory.class);
        FACTORIES.add(DayOfWeekFunctionFactory.class);
        FACTORIES.add(DayOfWeekSundayFirstFunctionFactory.class);
        FACTORIES.add(DaysPerMonthFunctionFactory.class);
        FACTORIES.add(ExtractFromTimestampFunctionFactory.class);
        FACTORIES.add(HourOfDayFunctionFactory.class);
        FACTORIES.add(IsEndOfMonthFunctionFactory.class);
        FACTORIES.add(IsLeapYearFunctionFactory.class);
        FACTORIES.add(MicrosOfMillsFunctionFactory.class);
        FACTORIES.add(MillisOfSecondFunctionFactory.class);
        FACTORIES.add(MinuteOfHourFunctionFactory.class);
        FACTORIES.add(MonthOfYearFunctionFactory.class);
        FACTORIES.add(NanosOfMicrosFunctionFactory.class);
        FACTORIES.add(SecondOfMinuteFunctionFactory.class);
        FACTORIES.add(TimestampAddFunctionFactory.class);
        FACTORIES.add(TimestampCeilFunctionFactory.class);
        FACTORIES.add(TimestampDiffFunctionFactory.class);
        FACTORIES.add(TimestampFloorFunctionFactory.class);
        FACTORIES.add(TimestampFloorFromFunctionFactory.class);
        FACTORIES.add(TimestampFloorFromOffsetUtcFunctionFactory.class);
        FACTORIES.add(ToDateFunctionFactory.class);
        FACTORIES.add(ToNanoTimestampFunctionFactory.class);
        FACTORIES.add(ToNanoTimestampVCFunctionFactory.class);
        FACTORIES.add(ToStrDateFunctionFactory.class);
        FACTORIES.add(ToStrTimestampFunctionFactory.class);
        FACTORIES.add(ToTimestampFunctionFactory.class);
        FACTORIES.add(ToTimestampVCFunctionFactory.class);
        FACTORIES.add(ToTimezoneTimestampFunctionFactory.class);
        FACTORIES.add(ToUTCTimestampFunctionFactory.class);
        FACTORIES.add(WeekOfYearFunctionFactory.class);
        FACTORIES.add(YearFunctionFactory.class);
        FACTORIES.add(EqDateFunctionFactory.class);
        FACTORIES.add(EqCharCharFunctionFactory.class);
        FACTORIES.add(LtDateFunctionFactory.class);
        FACTORIES.add(LtCharFunctionFactory.class);
        FACTORIES.add(InLongFunctionFactory.class);
        FACTORIES.add(InDoubleFunctionFactory.class);
        FACTORIES.add(BetweenTimestampFunctionFactory.class);
        FACTORIES.add(InTimestampTimestampFunctionFactory.class);
        FACTORIES.add(CastIPv4ToStrFunctionFactory.class);
        FACTORIES.add(LeftStrFunctionFactory.class);
        FACTORIES.add(RightStrFunctionFactory.class);
        FACTORIES.add(SubStringFunctionFactory.class);
        FACTORIES.add(ReplaceStrFunctionFactory.class);
        FACTORIES.add(StrPosFunctionFactory.class);
        FACTORIES.add(PositionFunctionFactory.class);
        FACTORIES.add(LeftVarcharFunctionFactory.class);
        FACTORIES.add(RightVarcharFunctionFactory.class);
        FACTORIES.add(SubStringVarcharFunctionFactory.class);
        FACTORIES.add(ReplaceVarcharFunctionFactory.class);
        FACTORIES.add(StrPosVarcharFunctionFactory.class);
        FACTORIES.add(PositionVarcharFunctionFactory.class);
        FACTORIES.add(ConcatFunctionFactory.class);
        FACTORIES.add(LengthVarcharFunctionFactory.class);
        FACTORIES.add(LengthBytesVarcharFunctionFactory.class);
        FACTORIES.add(LowerVarcharFunctionFactory.class);
        FACTORIES.add(UpperVarcharFunctionFactory.class);
        FACTORIES.add(ToLowercaseVarcharFunctionFactory.class);
        FACTORIES.add(ToUppercaseVarcharFunctionFactory.class);
        FACTORIES.add(TrimVarcharFunctionFactory.class);
        FACTORIES.add(LTrimVarcharFunctionFactory.class);
        FACTORIES.add(RTrimVarcharFunctionFactory.class);
        FACTORIES.add(CastStrToVarcharFunctionFactory.class);
        FACTORIES.add(CastVarcharToStrFunctionFactory.class);
        FACTORIES.add(EqSymStrFunctionFactory.class);
        FACTORIES.add(EqSymCharFunctionFactory.class);
        FACTORIES.add(EqSymFunctionFactory.class);
        FACTORIES.add(InSymbolFunctionFactory.class);
        FACTORIES.add(LikeSymbolFunctionFactory.class);
        FACTORIES.add(ILikeSymbolFunctionFactory.class);
        FACTORIES.add(LengthSymbolFunctionFactory.class);
        FACTORIES.add(CastSymbolToStrFunctionFactory.class);
        FACTORIES.add(CastSymbolToVarcharFunctionFactory.class);
        FACTORIES.add(EqVarcharFunctionFactory.class);
        FACTORIES.add(EqVarcharStrFunctionFactory.class);
        FACTORIES.add(LtVarcharFunctionFactory.class);
        FACTORIES.add(LtStrVarcharFunctionFactory.class);
        FACTORIES.add(LtVarcharStrFunctionFactory.class);
        FACTORIES.add(StartsWithStrFunctionFactory.class);
        FACTORIES.add(StartsWithVarcharFunctionFactory.class);
        FACTORIES.add(InStrFunctionFactory.class);
        FACTORIES.add(InVarcharFunctionFactory.class);
        FACTORIES.add(NullIfStrFunctionFactory.class);
        FACTORIES.add(NullIfVarcharFunctionFactory.class);
        FACTORIES.add(LikeStrFunctionFactory.class);
        FACTORIES.add(ILikeStrFunctionFactory.class);
        FACTORIES.add(LikeVarcharFunctionFactory.class);
        FACTORIES.add(ILikeVarcharFunctionFactory.class);
        FACTORIES.add(LengthStrFunctionFactory.class);
        FACTORIES.add(LowerFunctionFactory.class);
        FACTORIES.add(UpperFunctionFactory.class);
        FACTORIES.add(ToLowercaseFunctionFactory.class);
        FACTORIES.add(ToUppercaseFunctionFactory.class);
        FACTORIES.add(TrimStrFunctionFactory.class);
        FACTORIES.add(LTrimStrFunctionFactory.class);
        FACTORIES.add(RTrimStrFunctionFactory.class);
        FACTORIES.add(CaseFunctionFactory.class);
        FACTORIES.add(SwitchFunctionFactory.class);
        FACTORIES.add(AndFunctionFactory.class);
        FACTORIES.add(BitwiseAndIntFunctionFactory.class);
        FACTORIES.add(BitwiseAndLongFunctionFactory.class);
        FACTORIES.add(BitwiseNotIntFunctionFactory.class);
        FACTORIES.add(BitwiseNotLongFunctionFactory.class);
        FACTORIES.add(BitwiseOrIntFunctionFactory.class);
        FACTORIES.add(BitwiseOrLongFunctionFactory.class);
        FACTORIES.add(BitwiseXorIntFunctionFactory.class);
        FACTORIES.add(BitwiseXorLongFunctionFactory.class);
        FACTORIES.add(CastBooleanToByteFunctionFactory.class);
        FACTORIES.add(CastBooleanToCharFunctionFactory.class);
        FACTORIES.add(CastBooleanToDoubleFunctionFactory.class);
        FACTORIES.add(CastBooleanToFloatFunctionFactory.class);
        FACTORIES.add(CastBooleanToIntFunctionFactory.class);
        FACTORIES.add(CastBooleanToLongFunctionFactory.class);
        FACTORIES.add(CastBooleanToShortFunctionFactory.class);
        FACTORIES.add(CastBooleanToStrFunctionFactory.class);
        FACTORIES.add(CastBooleanToVarcharFunctionFactory.class);
        FACTORIES.add(CastByteToBooleanFunctionFactory.class);
        FACTORIES.add(CastByteToCharFunctionFactory.class);
        FACTORIES.add(CastByteToDoubleFunctionFactory.class);
        FACTORIES.add(CastByteToFloatFunctionFactory.class);
        FACTORIES.add(CastByteToIntFunctionFactory.class);
        FACTORIES.add(CastByteToLongFunctionFactory.class);
        FACTORIES.add(CastByteToShortFunctionFactory.class);
        FACTORIES.add(CastByteToStrFunctionFactory.class);
        FACTORIES.add(CastByteToVarcharFunctionFactory.class);
        FACTORIES.add(CastCharToBooleanFunctionFactory.class);
        FACTORIES.add(CastCharToByteFunctionFactory.class);
        FACTORIES.add(CastCharToDoubleFunctionFactory.class);
        FACTORIES.add(CastCharToFloatFunctionFactory.class);
        FACTORIES.add(CastCharToIntFunctionFactory.class);
        FACTORIES.add(CastCharToLongFunctionFactory.class);
        FACTORIES.add(CastCharToShortFunctionFactory.class);
        FACTORIES.add(CastCharToStrFunctionFactory.class);
        FACTORIES.add(CastCharToVarcharFunctionFactory.class);
        FACTORIES.add(CastDoubleToBooleanFunctionFactory.class);
        FACTORIES.add(CastDoubleToByteFunctionFactory.class);
        FACTORIES.add(CastDoubleToCharFunctionFactory.class);
        FACTORIES.add(CastDoubleToShortFunctionFactory.class);
        FACTORIES.add(CastDoubleToStrFunctionFactory.class);
        FACTORIES.add(CastDoubleToVarcharFunctionFactory.class);
        FACTORIES.add(CastFloatToBooleanFunctionFactory.class);
        FACTORIES.add(CastFloatToByteFunctionFactory.class);
        FACTORIES.add(CastFloatToCharFunctionFactory.class);
        FACTORIES.add(CastFloatToShortFunctionFactory.class);
        FACTORIES.add(CastFloatToStrFunctionFactory.class);
        FACTORIES.add(CastFloatToVarcharFunctionFactory.class);
        FACTORIES.add(CastIntToBooleanFunctionFactory.class);
        FACTORIES.add(CastIntToByteFunctionFactory.class);
        FACTORIES.add(CastIntToCharFunctionFactory.class);
        FACTORIES.add(CastIntToShortFunctionFactory.class);
        FACTORIES.add(CastIntToStrFunctionFactory.class);
        FACTORIES.add(CastIntToVarcharFunctionFactory.class);
        FACTORIES.add(CastLongToBooleanFunctionFactory.class);
        FACTORIES.add(CastLongToByteFunctionFactory.class);
        FACTORIES.add(CastLongToCharFunctionFactory.class);
        FACTORIES.add(CastLongToShortFunctionFactory.class);
        FACTORIES.add(CastLongToStrFunctionFactory.class);
        FACTORIES.add(CastLongToVarcharFunctionFactory.class);
        FACTORIES.add(CastShortToBooleanFunctionFactory.class);
        FACTORIES.add(CastShortToByteFunctionFactory.class);
        FACTORIES.add(CastShortToCharFunctionFactory.class);
        FACTORIES.add(CastShortToDoubleFunctionFactory.class);
        FACTORIES.add(CastShortToFloatFunctionFactory.class);
        FACTORIES.add(CastShortToIntFunctionFactory.class);
        FACTORIES.add(CastShortToLongFunctionFactory.class);
        FACTORIES.add(CastShortToStrFunctionFactory.class);
        FACTORIES.add(CastShortToVarcharFunctionFactory.class);
        FACTORIES.add(CastStrToBooleanFunctionFactory.class);
        FACTORIES.add(CastStrToByteFunctionFactory.class);
        FACTORIES.add(CastStrToCharFunctionFactory.class);
        FACTORIES.add(CastStrToDoubleFunctionFactory.class);
        FACTORIES.add(CastStrToFloatFunctionFactory.class);
        FACTORIES.add(CastStrToIntFunctionFactory.class);
        FACTORIES.add(CastStrToLongFunctionFactory.class);
        FACTORIES.add(CastStrToShortFunctionFactory.class);
        FACTORIES.add(CastSymbolToByteFunctionFactory.class);
        FACTORIES.add(CastSymbolToCharFunctionFactory.class);
        FACTORIES.add(CastSymbolToDoubleFunctionFactory.class);
        FACTORIES.add(CastSymbolToFloatFunctionFactory.class);
        FACTORIES.add(CastSymbolToIntFunctionFactory.class);
        FACTORIES.add(CastSymbolToLongFunctionFactory.class);
        FACTORIES.add(CastSymbolToShortFunctionFactory.class);
        FACTORIES.add(CastVarcharToBooleanFunctionFactory.class);
        FACTORIES.add(CastVarcharToByteFunctionFactory.class);
        FACTORIES.add(CastVarcharToCharFunctionFactory.class);
        FACTORIES.add(CastVarcharToDoubleFunctionFactory.class);
        FACTORIES.add(CastVarcharToFloatFunctionFactory.class);
        FACTORIES.add(CastVarcharToIntFunctionFactory.class);
        FACTORIES.add(CastVarcharToLongFunctionFactory.class);
        FACTORIES.add(CastVarcharToShortFunctionFactory.class);
        FACTORIES.add(CastDoubleToFloatFunctionFactory.class);
        FACTORIES.add(CastDoubleToIntFunctionFactory.class);
        FACTORIES.add(CastDoubleToLongFunctionFactory.class);
        FACTORIES.add(CastFloatToDoubleFunctionFactory.class);
        FACTORIES.add(CastFloatToIntFunctionFactory.class);
        FACTORIES.add(CastFloatToLongFunctionFactory.class);
        FACTORIES.add(CastIntToDoubleFunctionFactory.class);
        FACTORIES.add(CastIntToFloatFunctionFactory.class);
        FACTORIES.add(CastIntToLongFunctionFactory.class);
        FACTORIES.add(CastLongToDoubleFunctionFactory.class);
        FACTORIES.add(CastLongToFloatFunctionFactory.class);
        FACTORIES.add(CastLongToIntFunctionFactory.class);
        FACTORIES.add(CastBooleanToDateFunctionFactory.class);
        FACTORIES.add(CastBooleanToTimestampFunctionFactory.class);
        FACTORIES.add(CastByteToDateFunctionFactory.class);
        FACTORIES.add(CastByteToTimestampFunctionFactory.class);
        FACTORIES.add(CastCharToDateFunctionFactory.class);
        FACTORIES.add(CastCharToTimestampFunctionFactory.class);
        FACTORIES.add(CastDateToBooleanFunctionFactory.class);
        FACTORIES.add(CastDateToByteFunctionFactory.class);
        FACTORIES.add(CastDateToCharFunctionFactory.class);
        FACTORIES.add(CastDateToDoubleFunctionFactory.class);
        FACTORIES.add(CastDateToFloatFunctionFactory.class);
        FACTORIES.add(CastDateToIntFunctionFactory.class);
        FACTORIES.add(CastDateToLongFunctionFactory.class);
        FACTORIES.add(CastDateToShortFunctionFactory.class);
        FACTORIES.add(CastDateToStrFunctionFactory.class);
        FACTORIES.add(CastDateToTimestampFunctionFactory.class);
        FACTORIES.add(CastDateToVarcharFunctionFactory.class);
        FACTORIES.add(CastDoubleToDateFunctionFactory.class);
        FACTORIES.add(CastDoubleToTimestampFunctionFactory.class);
        FACTORIES.add(CastFloatToDateFunctionFactory.class);
        FACTORIES.add(CastFloatToTimestampFunctionFactory.class);
        FACTORIES.add(CastIPv4ToIntFunctionFactory.class);
        FACTORIES.add(CastIPv4ToVarcharFunctionFactory.class);
        FACTORIES.add(CastIntToDateFunctionFactory.class);
        FACTORIES.add(CastIntToIPv4FunctionFactory.class);
        FACTORIES.add(CastIntToTimestampFunctionFactory.class);
        FACTORIES.add(CastLongToDateFunctionFactory.class);
        FACTORIES.add(CastLongToTimestampFunctionFactory.class);
        FACTORIES.add(CastShortToDateFunctionFactory.class);
        FACTORIES.add(CastShortToTimestampFunctionFactory.class);
        FACTORIES.add(CastStrToDateFunctionFactory.class);
        FACTORIES.add(CastStrToIPv4FunctionFactory.class);
        FACTORIES.add(CastSymbolToDateFunctionFactory.class);
        FACTORIES.add(CastSymbolToTimestampFunctionFactory.class);
        FACTORIES.add(CastTimestampToBooleanFunctionFactory.class);
        FACTORIES.add(CastTimestampToByteFunctionFactory.class);
        FACTORIES.add(CastTimestampToCharFunctionFactory.class);
        FACTORIES.add(CastTimestampToDateFunctionFactory.class);
        FACTORIES.add(CastTimestampToDoubleFunctionFactory.class);
        FACTORIES.add(CastTimestampToFloatFunctionFactory.class);
        FACTORIES.add(CastTimestampToIntFunctionFactory.class);
        FACTORIES.add(CastTimestampToLongFunctionFactory.class);
        FACTORIES.add(CastTimestampToShortFunctionFactory.class);
        FACTORIES.add(CastTimestampToStrFunctionFactory.class);
        FACTORIES.add(CastTimestampToTimestampFunctionFactory.class);
        FACTORIES.add(CastTimestampToVarcharFunctionFactory.class);
        FACTORIES.add(CastVarcharToDateFunctionFactory.class);
        FACTORIES.add(CastVarcharToIPv4FunctionFactory.class);
        FACTORIES.add(CastVarcharToTimestampFunctionFactory.class);
        FACTORIES.add(DoubleArrayPositionFunctionFactory.class);
        FACTORIES.add(DoubleArrayInsertionPointFunctionFactory.class);
        FACTORIES.add(DoubleArrayInsertionPointAfterEqualFunctionFactory.class);
        FACTORIES.add(DoubleArrayElemAvgFunctionFactory.class);
        FACTORIES.add(DoubleArrayElemMaxFunctionFactory.class);
        FACTORIES.add(DoubleArrayElemMinFunctionFactory.class);
        FACTORIES.add(DoubleArrayElemSumFunctionFactory.class);
        FACTORIES.add(DoubleArrayFlattenFunctionFactory.class);
        FACTORIES.add(DoubleArrayTransposeFunctionFactory.class);
        FACTORIES.add(DoubleArrayCumSumFunctionFactory.class);
        FACTORIES.add(DoubleArrayShiftFunctionFactory.class);
        FACTORIES.add(DoubleArrayShiftDefaultNaNFunctionFactory.class);
        FACTORIES.add(DoubleArrayRoundFunctionFactory.class);
        FACTORIES.add(EqDoubleArrayFunctionFactory.class);
        FACTORIES.add(ArrayCreateFunctionFactory.class);
        FACTORIES.add(DoubleArrayAvgFunctionFactory.class);
        FACTORIES.add(DoubleArrayCountFunctionFactory.class);
        FACTORIES.add(DoubleArrayMaxFunctionFactory.class);
        FACTORIES.add(DoubleArrayMinFunctionFactory.class);
        FACTORIES.add(DoubleArrayReverseFunctionFactory.class);
        FACTORIES.add(DoubleArraySortDescFunctionFactory.class);
        FACTORIES.add(DoubleArraySortFullFunctionFactory.class);
        FACTORIES.add(DoubleArraySortFunctionFactory.class);
        FACTORIES.add(DoubleArrayStdDevFunctionFactory.class);
        FACTORIES.add(DoubleArrayStdDevPopFunctionFactory.class);
        FACTORIES.add(DoubleArrayStdDevSampFunctionFactory.class);
        FACTORIES.add(DoubleArraySumFunctionFactory.class);
        FACTORIES.add(IntIntervalFunctionFactory.class);
        FACTORIES.add(IntIntervalRightOpenFunctionFactory.class);
        FACTORIES.add(CastBooleanToLong256FunctionFactory.class);
        FACTORIES.add(CastByteToLong256FunctionFactory.class);
        FACTORIES.add(CastCharToLong256FunctionFactory.class);
        FACTORIES.add(CastDateToLong256FunctionFactory.class);
        FACTORIES.add(CastDoubleToLong256FunctionFactory.class);
        FACTORIES.add(CastFloatToLong256FunctionFactory.class);
        FACTORIES.add(CastGeoHashToGeoHashFunctionFactory.class);
        FACTORIES.add(CastGeoHashToStrFunctionFactory.class);
        FACTORIES.add(CastGeoHashToVarcharFunctionFactory.class);
        FACTORIES.add(CastIntToLong256FunctionFactory.class);
        FACTORIES.add(CastLong256ToBooleanFunctionFactory.class);
        FACTORIES.add(CastLong256ToByteFunctionFactory.class);
        FACTORIES.add(CastLong256ToCharFunctionFactory.class);
        FACTORIES.add(CastLong256ToDateFunctionFactory.class);
        FACTORIES.add(CastLong256ToDoubleFunctionFactory.class);
        FACTORIES.add(CastLong256ToFloatFunctionFactory.class);
        FACTORIES.add(CastLong256ToIntFunctionFactory.class);
        FACTORIES.add(CastLong256ToLongFunctionFactory.class);
        FACTORIES.add(CastLong256ToShortFunctionFactory.class);
        FACTORIES.add(CastLong256ToStrFunctionFactory.class);
        FACTORIES.add(CastLong256ToSymbolFunctionFactory.class);
        FACTORIES.add(CastLong256ToTimestampFunctionFactory.class);
        FACTORIES.add(CastLong256ToVarcharFunctionFactory.class);
        FACTORIES.add(CastLongToGeoHashFunctionFactory.class);
        FACTORIES.add(CastLongToLong256FunctionFactory.class);
        FACTORIES.add(CastShortToLong256FunctionFactory.class);
        FACTORIES.add(CastStrToGeoHashFunctionFactory.class);
        FACTORIES.add(CastStrToLong256FunctionFactory.class);
        FACTORIES.add(CastStrToUuidFunctionFactory.class);
        FACTORIES.add(CastSymbolToLong256FunctionFactory.class);
        FACTORIES.add(CastTimestampToLong256FunctionFactory.class);
        FACTORIES.add(CastUuidToStrFunctionFactory.class);
        FACTORIES.add(CastUuidToVarcharFunctionFactory.class);
        FACTORIES.add(CastVarcharToGeoHashFunctionFactory.class);
        FACTORIES.add(CastVarcharToLong256FunctionFactory.class);
        FACTORIES.add(CastVarcharToUuidFunctionFactory.class);
        FACTORIES.add(CastNullTypeFunctionFactory.class);
        FACTORIES.add(CastStrToTimestampFunctionFactory.class);
        FACTORIES.add(DivDoubleFunctionFactory.class);
        FACTORIES.add(DivFloatFunctionFactory.class);
        FACTORIES.add(DivIntFunctionFactory.class);
        FACTORIES.add(DivLongFunctionFactory.class);
        FACTORIES.add(EqDoubleFunctionFactory.class);
        FACTORIES.add(EqIntFunctionFactory.class);
        FACTORIES.add(EqIPv4FunctionFactory.class);
        FACTORIES.add(EqIPv4StrFunctionFactory.class);
        FACTORIES.add(EqUuidFunctionFactory.class);
        FACTORIES.add(EqUuidStrFunctionFactory.class);
        FACTORIES.add(EqLong256FunctionFactory.class);
        FACTORIES.add(EqLong256StrFunctionFactory.class);
        FACTORIES.add(EqIntStrCFunctionFactory.class);
        FACTORIES.add(EqLongFunctionFactory.class);
        FACTORIES.add(EqSymLongFunctionFactory.class);
        FACTORIES.add(EqTimestampFunctionFactory.class);
        FACTORIES.add(EqSymTimestampFunctionFactory.class);
        FACTORIES.add(EqStrCharFunctionFactory.class);
        FACTORIES.add(EqStrFunctionFactory.class);
        FACTORIES.add(LtDoubleVVFunctionFactory.class);
        FACTORIES.add(LtIntFunctionFactory.class);
        FACTORIES.add(LtLongFunctionFactory.class);
        FACTORIES.add(LtTimestampFunctionFactory.class);
        FACTORIES.add(LtStrFunctionFactory.class);
        FACTORIES.add(MulDoubleFunctionFactory.class);
        FACTORIES.add(MulFloatFunctionFactory.class);
        FACTORIES.add(MulIntFunctionFactory.class);
        FACTORIES.add(MulLongFunctionFactory.class);
        FACTORIES.add(NegDoubleFunctionFactory.class);
        FACTORIES.add(NegFloatFunctionFactory.class);
        FACTORIES.add(NegIntFunctionFactory.class);
        FACTORIES.add(NegLongFunctionFactory.class);
        FACTORIES.add(NotFunctionFactory.class);
        FACTORIES.add(NullIfDoubleFunctionFactory.class);
        FACTORIES.add(NullIfIntFunctionFactory.class);
        FACTORIES.add(NullIfLongFunctionFactory.class);
        FACTORIES.add(OrFunctionFactory.class);
        FACTORIES.add(SubDoubleFunctionFactory.class);
        FACTORIES.add(SubFloatFunctionFactory.class);
        FACTORIES.add(SubIntFunctionFactory.class);
        FACTORIES.add(SubLongFunctionFactory.class);
        FACTORIES.add(SubTimestampFunctionFactory.class);
    }
}
