/*+*****************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.griffin;

import io.questdb.cairo.ColumnType;
import io.questdb.griffin.model.QueryModel;
import io.questdb.griffin.plan.logical.LogicalPlan;
import io.questdb.griffin.plan.logical.OutputSchema;
import io.questdb.griffin.plan.logical.SetOperationPlan;
import io.questdb.std.Decimals;
import io.questdb.std.IntList;
import io.questdb.std.Numbers;
import org.jetbrains.annotations.TestOnly;

import static io.questdb.cairo.ColumnType.*;

/** Binding-side typing of UNION/EXCEPT/INTERSECT: output column types, symbol columns and timestamp. */
public final class SetOperationBinder {
    // @formatter:off
    /**
     * Autogenerated. See `SqlCodeGeneratorTest.testUnionCastMatrix`.
     * <p>
     * The UNION_CAST_MATRIX captures all the combinations of "left" and "right" column types
     * in a set operation (UNION etc.), providing the desired output type. Since there are many
     * special cases in the conversion logic, we decided to use a matrix of literals instead.
     * The matrix doesn't cover generic types (e.g. geohash) since they have a more complex structure.
     */
    private static final int[][] UNION_CAST_MATRIX = new int[][]{
            { 0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  0}, //  0 = unknown
            {11,  1, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  1}, //  1 = BOOLEAN
            {11, 11,  2,  3, 11,  5,  6,  7,  8,  9, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  2}, //  2 = BYTE
            {11, 11,  3,  3,  3,  5,  6,  7,  8,  9, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  3}, //  3 = SHORT
            {11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 11}, //  4 = CHAR
            {11, 11,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  5}, //  5 = INT
            {11, 11,  6,  6,  6,  6,  6,  7,  8,  9, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  6}, //  6 = LONG
            {11, 11,  7,  7,  7,  7,  7,  7,  8,  9, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  7}, //  7 = DATE
            {11, 11,  8,  8,  8,  8,  8,  8,  8,  9, 10, 11,  8, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  8}, //  8 = TIMESTAMP
            {11, 11,  9,  9,  9,  9,  9,  9,  9,  9, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26,  9}, //  9 = FLOAT
            {11, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 10}, // 10 = DOUBLE
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11}, // 11 = STRING
            {11, 11, 11, 11, 11, 11, 11, 11,  8, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 11}, // 12 = SYMBOL
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 13, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 13}, // 13 = LONG256
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 14 = GEOBYTE
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 15 = GEOSHORT
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 16 = GEOINT
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 17 = GEOLONG
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 18, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 18}, // 18 = BINARY
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 19, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 19}, // 19 = UUID
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 20, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 20}, // 20 = CURSOR
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 21, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 21}, // 21 = VARARG
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 22, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 22}, // 22 = RECORD
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 23, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 23}, // 23 = GEOHASH
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 24, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 24}, // 24 = LONG128
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 25, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 25}, // 25 = IPv4
            {26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 11, 26, 26, -1, -1, -1, -1, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, -1, -1, -1, -1, -1, -1, 26, 26, 26, 26, 26, 26, 26, 26}, // 26 = VARCHAR
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 27, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 26, 27}, // 27 = ARRAY
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 28 = DECIMAL8
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 29 = DECIMAL16
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 30 = DECIMAL32
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 31 = DECIMAL64
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 32 = DECIMAL128
            {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1}, // 33 = DECIMAL256
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 34, 11, 11, 11, 11, 11, 26, 34}, // 34 = DECIMAL
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 35, 11, 11, 11, 11, 26, 35}, // 35 = regclass
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 36, 11, 11, 11, 26, 36}, // 36 = regprocedure
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 37, 11, 11, 26, 37}, // 37 = text[]
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 38, 11, 26, 38}, // 38 = PARAMETER
            {11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, -1, -1, -1, -1, 11, 11, 11, 11, 11, 11, 11, 11, 26, 11, -1, -1, -1, -1, -1, -1, 11, 11, 11, 11, 11, 39, 26, 39}, // 39 = INTERVAL
            {26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 11, 26, 26, -1, -1, -1, -1, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, -1, -1, -1, -1, -1, -1, 26, 26, 26, 26, 26, 26, 26, 26}, // 40 = VARCHAR_SLICE
            { 0,  1,  2,  3, 11,  5,  6,  7,  8,  9, 10, 11, 11, 13, -1, -1, -1, -1, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, -1, -1, -1, -1, -1, -1, 34, 35, 36, 37, 38, 39, 26, 41}  // 41 = NULL
    };
    // @formatter:on

    private SetOperationBinder() {
    }

    @TestOnly
    public static int[][] actualUnionCastMatrix() {
        return UNION_CAST_MATRIX;
    }

    @TestOnly
    public static int[][] expectedUnionCastMatrix() {
        final int[][] expected = new int[NULL + 1][NULL + 1];
        for (int typeA = 0; typeA <= NULL; typeA++) {
            for (int typeB = 0; typeB <= NULL; typeB++) {
                final int outType = (isGeoType(typeA) || isGeoType(typeB) || isDecimalType(typeA) || isDecimalType(typeB)) ? -1 : commonWideningType(typeA, typeB);
                expected[typeA][typeB] = outType;
            }
        }
        return expected;
    }

    public static int getUnionCastType(int typeA, int typeB) throws SqlException {
        short tagA = tagOf(typeA);
        short tagB = tagOf(typeB);

        final boolean aIsArray = tagA == ARRAY;
        final boolean bIsArray = tagB == ARRAY;
        if (aIsArray && bIsArray) {
            short elementTypeA = decodeArrayElementType(typeA);
            if (elementTypeA != decodeArrayElementType(typeB)) {
                return VARCHAR;
            }
            int dimsA = decodeWeakArrayDimensionality(typeA);
            int dimsB = decodeWeakArrayDimensionality(typeB);
            if (dimsA == -1 || dimsB == -1) {
                throw SqlException.$(0, "array bind variables are not supported in UNION queries");
            }
            return encodeArrayType(elementTypeA, Math.max(dimsA, dimsB));
        } else if (aIsArray) {
            if (tagB == DOUBLE) {
                // if B is scalar then we coarse it to array of the same dimensionality as A is
                return typeA;
            }
            return (tagB == STRING) ? STRING : VARCHAR;
        } else if (bIsArray) {
            if (tagA == DOUBLE) {
                return typeB;
            }
            return (tagA == STRING ? STRING : VARCHAR);
        }

        int geoBitsA = getGeoHashBits(typeA);
        int geoBitsB = getGeoHashBits(typeB);
        boolean isGeoHashA = ColumnType.isGeoHash(typeA);
        boolean isGeoHashB = ColumnType.isGeoHash(typeB);
        if (isGeoHashA != isGeoHashB) {
            // One type is geohash, the other isn't. Since a stringy type can be parsed
            // into geohash, output geohash when the other type is stringy. If not,
            // cast both types to string.
            return isStringyType(typeA) ? typeB
                    : isStringyType(typeB) ? typeA
                      : STRING;
        }
        if (isGeoHashA) {
            // Both types are geohash, resolve to the one with fewer geohash bits.
            return geoBitsA < geoBitsB ? typeA : typeB;
        }

        boolean isDecimalA = ColumnType.isDecimalType(tagA);
        boolean isDecimalB = ColumnType.isDecimalType(tagB);
        if (isDecimalA || isDecimalB) {
            int a = DecimalUtil.getTypePrecisionScale(typeA);
            int b = DecimalUtil.getTypePrecisionScale(typeB);
            if (a != 0 && b != 0) {
                // Both types are decimal/implicitly castable to decimal.
                int precisionA = Numbers.decodeLowShort(a);
                int scaleA = Numbers.decodeHighShort(a);
                int precisionB = Numbers.decodeLowShort(b);
                int scaleB = Numbers.decodeHighShort(b);
                final int scale = Math.max(scaleA, scaleB);
                final int precision = Math.min(Math.max(precisionA - scaleA, precisionB - scaleB) + scale, Decimals.MAX_PRECISION);
                return ColumnType.getDecimalType(precision, scale);
            }
            // We also support casting between decimal and stringy types.
            return isStringyType(typeA) ? typeB :
                    isStringyType(typeB) ? typeA :
                    ColumnType.STRING; // Fallback should be supported by any type
        }

        if (tagA == INTERVAL || tagB == INTERVAL) {
            if (tagA == INTERVAL && tagB == INTERVAL) {
                return Math.max(typeA, typeB);
            }
            if (tagA == INTERVAL && tagB == NULL) {
                return typeA;
            }
            if (tagB == INTERVAL && tagA == NULL) {
                return typeB;
            }
        }

        // Neither type is geohash, use the type cast matrix to resolve.
        int result = UNION_CAST_MATRIX[tagA][tagB];

        //  indicate at least one of typeA or typeB is timestamp(timestamp_ns) type
        if (result == TIMESTAMP) {
            if (isTimestamp(typeA) && isTimestamp(typeB)) {
                return getHigherPrecisionTimestampType(typeA, typeB);
            } else if (isTimestamp(typeA)) {
                return typeA;
            } else {
                return typeB;
            }
        }
        return result;
    }

    static boolean isCastRequired(SetOperationPlan plan) {
        final OutputSchema left = plan.getLeft().getOutput();
        final OutputSchema right = plan.getRight().getOutput();
        for (int i = 0, n = left.getColumnCount(); i < n; i++) {
            final int type = left.getColumnType(i);
            if (type != right.getColumnType(i) || isUnion(plan.getOperation()) && ColumnType.isSymbol(type)) {
                return true;
            }
        }
        return false;
    }

    static boolean isSymbolTableStatic(SetOperationPlan plan, int index) {
        return !isUnion(plan.getOperation()) && !isCastRequired(plan)
                && plan.getLeft().getOutput().isSymbolTableStatic(index);
    }

    static boolean isUnion(int operation) {
        return operation == QueryModel.SET_OPERATION_UNION || operation == QueryModel.SET_OPERATION_UNION_ALL;
    }

    static int resolveTimestampIndex(SetOperationPlan plan) {
        return isUnion(plan.getOperation()) || isCastRequired(plan)
                ? -1 : plan.getLeft().getOutput().getTimestampIndex();
    }

    static void resolveTypes(SetOperationPlan plan, IntList targetTypes) throws SqlException {
        final OutputSchema left = plan.getLeft().getOutput();
        final OutputSchema right = plan.getRight().getOutput();
        if (left.getColumnCount() != right.getColumnCount()) {
            throw SqlException.$(plan.getRightPosition(), "queries have different number of columns");
        }
        final boolean union = isUnion(plan.getOperation());
        final boolean castRequired = isCastRequired(plan);
        targetTypes.clear();
        plan.getSymbolColumns().clear();
        for (int i = 0, n = left.getColumnCount(); i < n; i++) {
            int type = castRequired
                    ? getUnionCastType(left.getColumnType(i), right.getColumnType(i))
                    : left.getColumnType(i);
            if (union && isSymbolColumn(plan.getLeft(), i) && isSymbolColumn(plan.getRight(), i)) {
                plan.getSymbolColumns().add(i);
                if (plan.isSymbolRestorationRequired()) {
                    type = ColumnType.SYMBOL;
                }
            }
            targetTypes.add(type);
        }
    }

    private static boolean isSymbolColumn(LogicalPlan plan, int index) {
        return ColumnType.isSymbol(plan.getOutput().getColumnType(index))
                || plan instanceof SetOperationPlan operation && !operation.isSymbolRestorationRequired()
                && operation.getSymbolColumns().contains(index);
    }
}
