/*+*****************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.test.griffin.fuzz.expr;

/**
 * A typed literal generated by a {@link io.questdb.test.griffin.fuzz.types.FuzzColumnType}.
 * Carries the SQL-ready text used in literal form, plus optional pieces used
 * to substitute the constant for a bind variable in the differential
 * bind-variable form. When {@code bindCastDdl == null} the constant is not
 * bindable (e.g. {@code null} literals or types whose value is not safely
 * round-trippable through {@code setStr}); the bind path falls back to the
 * literal text in that case.
 *
 * @param literal     SQL text emitted in literal form (e.g. {@code 123}, {@code 'abc'::VARCHAR}).
 * @param bindCastDdl type DDL appended after {@code ?::} in bind form (e.g. {@code INT},
 *                    {@code VARCHAR}); {@code null} means not bindable.
 * @param bindValue   string value bound via {@code BindVariableService.setStr}; ignored
 *                    when {@code bindCastDdl == null}.
 */
public record FuzzConstant(String literal, String bindCastDdl, String bindValue) {

    public static FuzzConstant nonBindable(String literal) {
        return new FuzzConstant(literal, null, null);
    }

    public boolean isBindable() {
        return bindCastDdl != null;
    }
}
