[package]
name = "s3"
version = "0.1.0"
edition = "2018"

[dependencies]
parquet2 = { path = "../../" }
rust-s3 = { version = "0.27.0-rc4", features = ["blocking", "futures"] }
futures = "0.3"
tokio = { version = "1.0.0", features = ["macros", "rt-multi-thread"] }
