name: Bug report
description: Create a bug report to help us improve QuestDB
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the bug.  
        ❗ Please provide all the required information to receive faster responses from the maintainers. 
  - type: textarea
    attributes:
      label: Describe the bug
      description: A concise description of what you're experiencing.
  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce this behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Run this SQL '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        Provide details about your environment if applicable, for example:
          - **QuestDB version**: 6.0.9
          - **OS**: Ubuntu 20.04
          - **Browser**: Firefox 93.0 (64-bit)

      value: |
        - **QuestDB version**:
        - **OS**:
        - **Browser**:
      render: markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Please add screenshots, logs files, links, or details that provide context about the issue.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
