FROM debian:stable-20191014-slim

ENV JRE jre-8u231-linux-x64.tar.gz
ENV JRE_DIR jre1.8.0_231
ENV QUESTDB_VERSION 3.5.0-SNAPSHOT

# install 'ps' command needed by questdb shell script
RUN apt-get update && apt-get install -y procps

# Copy the binary file into the container at /app
COPY target/questdb-${QUESTDB_VERSION}-bin.tar.gz /app/

# Copy win64 JDK into the container at /app
COPY dist/${JRE} /app/

WORKDIR /app

# Install questdb
RUN tar xvfz questdb-${QUESTDB_VERSION}-bin.tar.gz

# install JRE8
RUN tar xvfz ${JRE}

# remove JRE tarball
RUN rm ${JRE}

# Make working folder the quest db folder
WORKDIR /app/questdb-${QUESTDB_VERSION}

# Make port 9000 available to the world outside this container
EXPOSE 9000/tcp

# Run questdb when the container launches
CMD export JAVA_HOME=/app/${JRE_DIR}; ./questdb.sh start -c
