FROM microsoft/nanoserver:1803

ENV JRE jre-8u231-windows-x64.tar.gz

# Copy the binary file into the container at /app
COPY target/questdb-3.5.0-SNAPSHOT-bin.tar.gz /app/

# Copy win64 JDK into the container at /app
COPY dist/${JRE} /app/

WORKDIR /app

# Install questdb
RUN tar.exe xvfz questdb-3.5.0-SNAPSHOT-bin.tar.gz

# install JRE8
RUN tar xvfz %JRE%

# remove JRE tarball
RUN del %JRE%

# Make working folder the quest db folder
WORKDIR /app/questdb-3.5.0-SNAPSHOT

# Make port 9000 available to the world outside this container
EXPOSE 9000/tcp

# Run questdb when the container launches
CMD questdb.exe -j c:\app\jre1.8.0_231
