/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nfsdb_net_http_Win32SelectDispatcher */

#ifndef _Included_com_nfsdb_net_http_Win32SelectDispatcher
#define _Included_com_nfsdb_net_http_Win32SelectDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nfsdb_net_http_Win32SelectDispatcher
 * Method:    select
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_nfsdb_net_http_Win32SelectDispatcher_select
        (JNIEnv *, jclass, jlong, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_nfsdb_net_http_Win32SelectDispatcher_arrayOffset
        (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_nfsdb_net_http_Win32SelectDispatcher_countOffset
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
