jobs:
  - job: CheckChanges
    displayName: "Check changes"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: none
      - bash: |
          if [ -z "$PR_ID" ]
          then
            # No PR - cannot detect changed files, default to true
            echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
          else
            CHANGED_CORE_FILES=$(curl https://api.github.com/repos/questdb/questdb/pulls/$PR_ID/files -s  | grep -oP 'filename": "(core|benchmarks)/*\/\K[^.]+')
            if [ -z "$CHANGED_CORE_FILES" ]
              then
                echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
              else
                echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
            fi
          fi
        env:
          PR_ID: $(System.PullRequest.PullRequestNumber)
        name: check_changes
        displayName: "Check changed files"
