jobs:
  - job: CheckChanges
    displayName: "Check changes"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: none
        name: check_changes
        env:
          PRID: $(System.PullRequest.PullRequestNumber)
        displayName: "Check changed files"
      - bash: |
          echo $PRID
          if [[ $PRID =~ ^[0-9]+$ ]]; then
            PAGE=0
            while true; do
              PAGE=$((PAGE+1))
              echo PAGE $PAGE
              FILES=$(curl https://api.github.com/repos/questdb/questdb/pulls/$PRID/files\?per_page\=100\&page=$PAGE -s)
              ANY=$(echo $FILES | grep '"filename":')
              if [ -z "$ANY" ]; then
                if [ -n "$ALL_CHANGES" ]; then
                  echo "##vso[task.setvariable variable=COVERAGE_DIFF;isOutput=true]$ALL_CHANGES"
                  echo "##vso[task.setvariable variable=CODE_COVERAGE_TOOL_OPTION;isOutput=true]JaCoCo"
                else 
                  echo "##vso[task.setvariable variable=COVERAGE_DIFF;isOutput=true]-:*"
                  echo "##vso[task.setvariable variable=CODE_COVERAGE_TOOL_OPTION;isOutput=true]None"
                fi
          
                if [ -n "$CHANGED_CORE_FILES" ]; then
                  echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
                else
                  echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
                fi

                break
              fi
          
              COV_CLASSES=$(echo $FILES | jq -r '.[].filename' | grep '.java' | grep 'core/src/main/java' \
                  | sed 's#.*/##; s/\.java$//' \
                  | tr '\n' ',' | sed -e 's/,/,+:*./g' | sed 's/,+:\*\.$//')
          
              if [ -z "$COV_CLASSES" ]; then
                echo no match found
              else
                echo match found
                if [ -n "$ALL_CHANGES" ]; then
                  ALL_CHANGES="${ALL_CHANGES},+:*.${COV_CLASSES}"
                else
                  ALL_CHANGES="+:*.${COV_CLASSES}"
                fi
              fi
              CHANGED_CORE_FILES="${CHANGED_CORE_FILES}$(echo $FILES | jq -r '.[].filename' | grep -oP 'filename": "(core|benchmarks|compat|utils)/*\/\K[^.]+')"
            done
          fi
        name: check_coverage
        env:
          PRID: $(System.PullRequest.PullRequestNumber)
        displayName: "List of coverage classes PR build"
