jobs:
  - job: CheckChanges
    displayName: "Check changes"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - checkout: none
        name: check_changes
        env:
          PRID: $(System.PullRequest.PullRequestNumber)
        displayName: "Check changed files"
      - bash: |
          set -ux
          echo "PR ID: $PRID"
          if ! [[ $PRID =~ ^[0-9]+$ ]]; then
            exit(0)
          fi
          
          ALL_CHANGES=""
          CHANGED_CORE_FILES=""
          CHANGED_RUST_FILES=""
          
          PAGE=0
          while true; do
            PAGE=$((PAGE+1))
            echo PAGE $PAGE
            FILES=$(curl "https://api.github.com/repos/questdb/questdb/pulls/$PRID/files?per_page=2&page=$PAGE" -s)
            ANY=$(echo "$FILES" | grep '"filename":')
            if [ -z "$ANY" ]; then
              if [ -n "$ALL_CHANGES" ]; then
                echo "##vso[task.setvariable variable=COVERAGE_DIFF;isOutput=true]$ALL_CHANGES"
                echo "##vso[task.setvariable variable=CODE_COVERAGE_TOOL_OPTION;isOutput=true]JaCoCo"
              else 
                echo "##vso[task.setvariable variable=COVERAGE_DIFF;isOutput=true]-:*"
                echo "##vso[task.setvariable variable=CODE_COVERAGE_TOOL_OPTION;isOutput=true]None"
              fi
          
              if [ -n "$CHANGED_CORE_FILES" ]; then
                echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]false"
              else
                echo "##vso[task.setvariable variable=SOURCE_CODE_CHANGED;isOutput=true]true"
              fi

              if [ -n "$CHANGED_RUST_FILES" ]; then
                echo "##vso[task.setvariable variable=RUST_SOURCE_CODE_CHANGED;isOutput=true]false"
              else
                echo "##vso[task.setvariable variable=RUST_SOURCE_CODE_CHANGED;isOutput=true]true"
              fi

              break
            fi
          
            COV_CLASSES=$(echo "$ANY" | grep -oP 'core/src/main/java/(.+/)?\K.+(?=\.java)' \
              | sed -e 's/^/+:*./g' | tr '\n' ',' )
          
            if [ ! -z "$COV_CLASSES" ]; then
              ALL_CHANGES="${ALL_CHANGES}${COV_CLASSES}"
            fi
            CHANGED_CORE_FILES="${CHANGED_CORE_FILES}$(echo "$ANY" | grep -oP 'filename": "\K(core|benchmarks|compat|utils)')"
            CHANGED_RUST_FILES="${CHANGED_RUST_FILES}$(echo "$ANY" | grep -oP 'filename": "\K(core/rust)')"
          done
          ALL_CHANGES=$(echo "$ALL_CHANGES" | sed -e 's/,$//g')
        name: check_coverage
        env:
          PRID: $(System.PullRequest.PullRequestNumber)
        displayName: "List of coverage classes PR build"
