jobs:
  - job: CheckChanges
    displayName: "Check changes"
    pool:
      vmImage: "ubuntu-latest"
    variables:
      SOURCE_CODE_CHANGED:
        $[stageDependencies.CheckChanges.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED']]
      CODE_COVERAGE_TOOL_OPTION:
        $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      IF_FORK:
        $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.IF_FORK']]
    steps:
      - checkout: self
        fetchDepth: 1
        lfs: false
        submodules: false
      - download: current
        artifact: jacocoreport
      - bash:
          $JAVA_HOME_11_X64/bin/java -jar
          $(Build.SourcesDirectory)/ci/cover-checker-console-1.4.2-jar-with-dependencies.jar -c
          $(Pipeline.Workspace)\jacocoreport\jacoco.xml --github-token $(GH_TOKEN) --repo
          "questdb/questdb" --pr $(System.PullRequest.PullRequestNumber) -t  $(DIFF_COVER_THRESHOLD_PCT) -type jacoco;
        displayName: "Diff coverage PR report"
        condition: |
          and(
            and(
              eq(variables['CODE_COVERAGE_TOOL_OPTION'], 'JaCoCo'),
              eq(variables['SOURCE_CODE_CHANGED'], 'true')
            ),
            eq(variables['$IF_FORK'], 'NO')
          )

