jobs:
  - job: RunOn
    displayName: "on"
    strategy:
      matrix:
        linux-griffin:
          imageName: "ubuntu-latest"
          poolName: "Azure Pipelines"
          os: Linux
          jdk: "1.11"
          testset: "coverage"
          includeTests: "griffin.**.*?"
        linux-cairo:
          imageName: "ubuntu-latest"
          poolName: "Azure Pipelines"
          os: Linux
          jdk: "1.11"
          testset: "coverage"
          includeTests: "cairo.**.*?"
        linux-other:
          imageName: "ubuntu-latest"
          poolName: "Azure Pipelines"
          os: Linux
          jdk: "1.11"
          testset: "coverage"
          excludeTests: "**/griffin/**,**/cairo/**"
    pool:
      vmImage: $(imageName)
      name: $(poolName)
    timeoutInMinutes: 60
    variables:
      SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED']]
      COVERAGE_DIFF: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.COVERAGE_DIFF']]
      CODE_COVERAGE_TOOL_OPTION: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
      MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m"
      ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
      ARCHIVED_HEAP_DUMP: "$(Build.ArtifactStagingDirectory)/questdb-heapdump-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).hprof"
    steps:
      - template: steps.yml
