jobs:
  - job: RunOn
    displayName: "on"
    strategy:
      matrix:
        mac-griffin:
          imageName: "macos-latest"
          poolName: "Azure Pipelines"
          os: macOS
          jdk: "1.11"
          testset: "all"
          includeTests: "griffin.**.*?"
          javadoc_step: ""
          javadoc_profile: ""
        mac-cairo:
          imageName: "macos-latest"
          poolName: "Azure Pipelines"
          os: macOS
          jdk: "1.11"
          testset: "all"
          includeTests: "cairo.**.*?"
          javadoc_step: ""
          javadoc_profile: ""
        mac-other:
          imageName: "macos-latest"
          poolName: "Azure Pipelines"
          os: macOS
          jdk: "1.11"
          testset: "all"
          excludeTests: "**/griffin/**,**/cairo/**"
          javadoc_step: ""
          javadoc_profile: ""
        windows-griffin:
          imageName: "windows-latest"
          poolName: "Azure Pipelines"
          os: Windows
          jdk: "1.11"
          testset: "all"
          includeTests: "griffin.**.*?"
          javadoc_step: ""
          javadoc_profile: ""
        windows-cairo:
          imageName: "windows-latest"
          poolName: "Azure Pipelines"
          os: Windows
          jdk: "1.11"
          testset: "all"
          includeTests: "cairo.**.*?"
          javadoc_step: ""
          javadoc_profile: ""
        windows-other:
          imageName: "windows-latest"
          poolName: "Azure Pipelines"
          os: Windows
          jdk: "1.11"
          testset: "all"
          excludeTests: "**/griffin/**,**/cairo/**"
          javadoc_step: ""
          javadoc_profile: ""
        linux-jdk8:
          imageName: "ubuntu-latest"
          poolName: "Azure Pipelines"
          os: Linux
          jdk: "1.8"
          testset: "none"
          javadoc_step: ""
          javadoc_profile: ""
        linux-jdk17:
          imageName: "ubuntu-latest"
          poolName: "Azure Pipelines"
          os: Linux
          jdk: "1.17"
          testset: "none"
          javadoc_step: "javadoc:javadoc"
          javadoc_profile: ",javadoc"
    pool:
      vmImage: $(imageName)
      name: $(poolName)
    timeoutInMinutes: 60
    variables:
      SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED']]
      COVERAGE_DIFF: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.COVERAGE_DIFF']]
      CODE_COVERAGE_TOOL_OPTION: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
      MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m"
      ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
      MAVEN_VERSION: 3.8.7
    steps:
      - template: steps.yml
