jobs:
- job: linux
  displayName: "on linux"
  pool:
    name: "Azure Pipelines"
    vmImage: "ubuntu-latest"
  dependsOn:
  - CheckChanges
  - Test
  timeoutInMinutes: 60
  variables:
    SOURCE_CODE_CHANGED: $[ dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'] ]
    MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
    MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'
    os: Linux
    jdk: "1.11"
  steps:
  - template: steps.yml
# - job: mac
#   displayName: "on mac"
#   pool:
#     name: "Azure Pipelines"
#     vmImage: "macos-latest"
#   dependsOn:
#   - CheckChanges
#   - Test
#   timeoutInMinutes: 60
#   variables:
#     SOURCE_CODE_CHANGED: $[ dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'] ]
#     MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
#     MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'
#     os: macOS
#     jdk: "1.11"
#   steps:
#   - template: steps.yml
# - job: windows
#   displayName: "on windows"
#   pool:
#     name: "Azure Pipelines"
#     vmImage: "windows-latest"
#   dependsOn:
#   - CheckChanges
#   - Test
#   timeoutInMinutes: 60
#   variables:
#     SOURCE_CODE_CHANGED: $[ dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'] ]
#     MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
#     MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'
#     os: Windows
#     jdk: "1.11"
#   steps:
#   - template: steps.yml
# - job: linux_jdk8
#   displayName: "on linux-jdk8"
#   pool:
#     name: "Azure Pipelines"
#     vmImage: "ubuntu-latest"
#   dependsOn:
#   - CheckChanges
#   - Test
#   timeoutInMinutes: 60
#   variables:
#     SOURCE_CODE_CHANGED: $[ dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'] ]
#     MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
#     MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'
#     os: Linux
#     jdk: "1.8"
#   steps:
#   - template: steps.yml
- job: linux_arm64
  displayName: "on linux-arm64"
  pool:
    name: "arm64"
    vmImage:
    demands:
    - Agent.Name -equals arm64-$(Build.BuildId)
  dependsOn:
  - CheckChanges
  - Test
  timeoutInMinutes: 60
  condition: eq(variables['System.PullRequest.IsFork'], 'false')
  variables:
    SOURCE_CODE_CHANGED: $[ dependencies.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED'] ]
    MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
    MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m'
    os: Linux
    jdk: "1.11"
  steps:
  - template: steps.yml
