jobs:
  - job: linux_arm64_jdk17
    workspace:
      clean: all
    displayName: "on linux-arm64"
    pool:
      name: "hetzner-docker-arm"
    timeoutInMinutes: 60
    condition: eq(variables['System.PullRequest.IsFork'], 'false')
    variables:
      SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.SOURCE_CODE_CHANGED']]
      RUST_SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.RUST_SOURCE_CODE_CHANGED']]
      CODE_COVERAGE_TOOL_OPTION: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      DIFF_COVER_THRESHOLD_PCT: 50
      ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
      testset: "all"
      javadoc_step: ""
      javadoc_profile: ""
      jdk: "1.17"
      JAVA_HOME_17_X64: "/usr/lib/jvm/java-17-openjdk-arm64"
      JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-arm64"
      os: Linux
    steps:
      - template: steps.yml

  - job: linux_x64_zfs_jdk17
    displayName: "on linux-x64-zfs"
    pool:
      name: "amd64-zfs"
      demands:
        - Agent.Name -equals amd64-zfs-$(System.StageName)$(Build.BuildId)
    dependsOn:
      - StartX64ZfsAgent
    timeoutInMinutes: 60
    condition: eq(variables['System.PullRequest.IsFork'], 'false')
    variables:
      SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.SOURCE_CODE_CHANGED']]
      RUST_SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.RUST_SOURCE_CODE_CHANGED']]
      CODE_COVERAGE_TOOL_OPTION: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      DIFF_COVER_THRESHOLD_PCT: 50
      ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
      testset: "all"
      javadoc_step: ""
      javadoc_profile: ""
      jdk: "1.17"
      os: Linux
      JAVA_HOME_17_X64: "/usr/lib/jvm/java-17-amazon-corretto.x86_64"
      JAVA_HOME: "/usr/lib/jvm/java-17-amazon-corretto.x86_64"
    steps:
      - template: steps.yml
