jobs:
  - job: linux_arm64_jdk17
    workspace:
      clean: all
    displayName: "on linux-arm64"
    strategy:
      matrix:
        arm64-griffin:
          testset: "all"
          includeTests: "**/griffin/**"
          javadoc_step: ""
          javadoc_profile: ""
        arm64-cairo:
          testset: "all"
          includeTests: "**/cairo/**"
          # Exclude cairo fuzz tests: run in arm64-cairo-fuzz
          excludeTests: "**/cairo/fuzz/**"
          javadoc_step: ""
          javadoc_profile: ""
        arm64-cairo-fuzz:
          testset: "all"
          includeTests: "**/cairo/fuzz/**"
          javadoc_step: ""
          javadoc_profile: ""
        arm64-pgwire:
          testset: "all"
          includeTests: "**/pgwire/**/*.java"
          javadoc_step: ""
          javadoc_profile: ""
        arm64-other:
          testset: "all"
          # Exclude griffin: run in arm64-griffin
          # Exclude cairo: run in arm64-cairo and arm64-cairo-fuzz
          # Exclude compat/cliutil: run in Linux (JavaAndRustLint stage)
          # Exclude pgwire: run in arm64-pgwire
          excludeTests: "**/griffin/**,**/cairo/**,**/compat/**,**/cliutil/**,**/pgwire/**"
          javadoc_step: ""
          javadoc_profile: ""
    pool:
      name: "hetzner-docker-arm"
    timeoutInMinutes: 60
    condition: eq(variables['System.PullRequest.IsFork'], 'false')
    variables:
      SOURCE_CODE_CHANGED: "true"
      RUST_SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.RUST_SOURCE_CODE_CHANGED']]
      CODE_COVERAGE_TOOL_OPTION: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      DIFF_COVER_THRESHOLD_PCT: 50
      ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
      testset: "all"
      javadoc_step: ""
      javadoc_profile: ""
      jdk: "1.17"
      JAVA_HOME_17_X64: "/usr/lib/jvm/java-17-openjdk-arm64"
      JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-arm64"
      os: Linux
    steps:
      - template: steps.yml

  - job: linux_x64_zfs_jdk17
    workspace:
      clean: all
    displayName: "on linux-x64-zfs"
    pool:
      name: "hetzner-docker-zfs"
    timeoutInMinutes: 60
    condition: eq(variables['System.PullRequest.IsFork'], 'false')
    variables:
      SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.SOURCE_CODE_CHANGED']]
      RUST_SOURCE_CODE_CHANGED: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.RUST_SOURCE_CODE_CHANGED']]
      CODE_COVERAGE_TOOL_OPTION: $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      DIFF_COVER_THRESHOLD_PCT: 50
      ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
      testset: "all"
      javadoc_step: ""
      javadoc_profile: ""
      jdk: "1.17"
      os: Linux
      JAVA_HOME_17_X64: "/usr/lib/jvm/java-17-openjdk-amd64"
      JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
    steps:
      - template: steps.yml
