jobs:
  - job: linux_arm64
    displayName: "on linux-arm64"
    pool:
      name: "arm64"
      vmImage:
      demands:
        - Agent.Name -equals arm64-$(Build.BuildId)
    dependsOn:
      - StartArmAgent
    timeoutInMinutes: 60
    condition: eq(variables['System.PullRequest.IsFork'], 'false')
    variables:
      testset: all
      SOURCE_CODE_CHANGED:
        $[stageDependencies.CheckChanges.CheckChanges.outputs['check_changes.SOURCE_CODE_CHANGED']]
      CODE_COVERAGE_TOOL_OPTION:
        $[stageDependencies.CheckChanges.CheckChanges.outputs['check_coverage.CODE_COVERAGE_TOOL_OPTION']]
      MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
      MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m"
      ARCHIVED_GRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
      os: Linux
      jdk: "1.11"
    steps:
      - template: steps.yml
