[package]
name = "qdb"
version = "0.1.0"
edition = "2021"

[lib]
name = "qdb"
crate-type = ["dylib"]

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

[dependencies]
qdb-core = { path = "../qdb-core" }
fail = "0.5.1"
