[package]
name = "qdb"
version = "0.1.0"
edition = "2021"

[lib]
name = "qdb"
crate-type = ["dylib", "rlib"]

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

[dependencies]
jni = "0.21.0"
