/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_questdb_std_DoubleConversion */

#ifndef _Included_io_questdb_std_DoubleConversion
#define _Included_io_questdb_std_DoubleConversion
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_questdb_std_DoubleConversion
 * Method:    append
 * Signature:
 */
JNIEXPORT jstring JNICALL Java_io_questdb_std_DoubleConversion_append
  (JNIEnv *, jclass, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
