/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nfsdb_misc_Files */

#ifndef _Included_com_nfsdb_misc_Files
#define _Included_com_nfsdb_misc_Files
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nfsdb_misc_Files
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_nfsdb_misc_Files_close
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_nfsdb_misc_Files
 * Method:    lastModified
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nfsdb_misc_Files_lastModified
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nfsdb_misc_Files
 * Method:    openRO
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nfsdb_misc_Files_openRO
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nfsdb_misc_Files
 * Method:    openRW
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_nfsdb_misc_Files_openRW
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nfsdb_misc_Files
 * Method:    read
 * Signature: (IJIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nfsdb_misc_Files_read
        (JNIEnv *, jclass, jint, jlong, jint, jlong);

/*
 * Class:     com_nfsdb_misc_Files
 * Method:    length
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_nfsdb_misc_Files_length
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nfsdb_misc_Files
 * Method:    write
 * Signature: (IJIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_nfsdb_misc_Files_write
        (JNIEnv *, jclass, jint, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
