/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_questdb_std_Files */

#ifndef _Included_com_questdb_std_Files
#define _Included_com_questdb_std_Files
#ifdef __cplusplus
extern "C" {
#endif
#undef com_questdb_std_Files_DT_UNKNOWN
#define com_questdb_std_Files_DT_UNKNOWN 0L
#undef com_questdb_std_Files_DT_FIFO
#define com_questdb_std_Files_DT_FIFO 1L
#undef com_questdb_std_Files_DT_CHR
#define com_questdb_std_Files_DT_CHR 2L
#undef com_questdb_std_Files_DT_DIR
#define com_questdb_std_Files_DT_DIR 4L
#undef com_questdb_std_Files_DT_BLK
#define com_questdb_std_Files_DT_BLK 6L
#undef com_questdb_std_Files_DT_REG
#define com_questdb_std_Files_DT_REG 8L
#undef com_questdb_std_Files_DT_LNK
#define com_questdb_std_Files_DT_LNK 10L
#undef com_questdb_std_Files_DT_SOCK
#define com_questdb_std_Files_DT_SOCK 12L
#undef com_questdb_std_Files_DT_WHT
#define com_questdb_std_Files_DT_WHT 14L
#undef com_questdb_std_Files_MAP_RO
#define com_questdb_std_Files_MAP_RO 1L
#undef com_questdb_std_Files_MAP_RW
#define com_questdb_std_Files_MAP_RW 2L
/*
 * Class:     com_questdb_std_Files
 * Method:    append
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_append
        (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    exists
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_questdb_std_Files_exists
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    findClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_questdb_std_Files_findClose
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    findName
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_findName
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    findNext
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_std_Files_findNext
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    findType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_std_Files_findType
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    getStdOutFd
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_getStdOutFd
        (JNIEnv *, jclass);

/*
 * Class:     com_questdb_std_Files
 * Method:    length
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_length
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    lock
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_std_Files_lock
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    openCleanRW
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_openCleanRW
        (JNIEnv *e, jclass cl, jlong lpszName, jlong size);

/*
 * Class:     com_questdb_std_Files
 * Method:    read
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_read
        (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    readUlong
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_readULong
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    truncate
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_questdb_std_Files_truncate
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    allocate
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_questdb_std_Files_allocate
        (JNIEnv *, jclass, jlong, jlong);        

/*
 * Class:     com_questdb_std_Files
 * Method:    write
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_write
        (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    close0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_std_Files_close0
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    copy
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_std_Files_close
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    munmap0
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_std_Files_munmap0
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    mmap0
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_mmap0
        (JNIEnv *, jclass, jlong, jlong, jlong, jint, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    mremap0
 * Signature: (JJJJJI)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_mremap0
        (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jlong, jint);

JNIEXPORT jlong JNICALL JavaCritical_io_questdb_std_Files_mremap0
        (jlong, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     com_questdb_std_Files
 * Method:    getPageSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_getPageSize
        (JNIEnv *, jclass);

/*
 * Class:     com_questdb_std_Files
 * Method:    remove
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_questdb_std_Files_remove
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    rmdir
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_questdb_std_Files_rmdir
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    getLastModified
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_getLastModified
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    length0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_length0
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    mkdir
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_io_questdb_std_Files_mkdir
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_questdb_std_Files
 * Method:    openRO
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_openRO
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    openRW
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_openRW
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    openAppend
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_openAppend
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    findFirst
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_questdb_std_Files_findFirst
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    setLastModified
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_io_questdb_std_Files_setLastModified
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_questdb_std_Files
 * Method:    rename
 * Signature: (JJ)I
 */

#define FILES_RENAME_ERR_OK 0
#define FILES_RENAME_ERR_EXDEV 1
#define FILES_RENAME_ERR_OTHER 2

JNIEXPORT jint JNICALL Java_io_questdb_std_Files_rename
        (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
