/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_questdb_std_Net */

#ifndef _Included_com_questdb_std_Net
#define _Included_com_questdb_std_Net
#ifdef __cplusplus
extern "C" {
#endif
#undef com_questdb_std_Net_ERETRY
#define com_questdb_std_Net_ERETRY 0L
#undef com_questdb_std_Net_EPEERDISCONNECT
#define com_questdb_std_Net_EPEERDISCONNECT -1L
#undef com_questdb_std_Net_EOTHERDISCONNECT
#define com_questdb_std_Net_EOTHERDISCONNECT -2L
/*
 * Class:     com_questdb_std_Net
 * Method:    accept
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_accept
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    bindTcp
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_questdb_std_Net_bindTcp
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    bindUdp
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_questdb_std_Net_bindUdp
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    configureNoLinger
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_configureNoLinger
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    configureNonBlocking
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_configureNonBlocking
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    connect
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_connect
        (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    freeMsgHeaders
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_questdb_std_Net_freeMsgHeaders
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    freeSockAddr
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_questdb_std_Net_freeSockAddr
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    getPeerIP
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_getPeerIP
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    getPeerPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_getPeerPort
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    isDead
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_questdb_std_Net_isDead
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    shutdownAll
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_shutdownAll
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    join
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_questdb_std_Net_join
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    listen
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_questdb_std_Net_listen
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    msgHeaders
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_msgHeaders
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    recv
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_recv
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    recvmmsg
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_recvmmsg
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    send
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_send
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    sendTo
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_sendTo
        (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     com_questdb_std_Net
 * Method:    setRcvBuf
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_setRcvBuf
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    setSndBuf
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_setSndBuf
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    sockaddr
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_sockaddr
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_questdb_std_Net
 * Method:    socketTcp
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_socketTcp
        (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_questdb_std_Net
 * Method:    socketUdp0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_socketUdp0
        (JNIEnv *, jclass);

/*
 * Class:     com_questdb_std_Net
 * Method:    getMsgHeaderSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_getMsgHeaderSize
        (JNIEnv *, jclass);

/*
 * Class:     com_questdb_std_Net
 * Method:    getMsgHeaderBufferAddressOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_getMsgHeaderBufferAddressOffset
        (JNIEnv *, jclass);

/*
 * Class:     com_questdb_std_Net
 * Method:    getMsgHeaderBufferLengthOffset
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_questdb_std_Net_getMsgHeaderBufferLengthOffset
        (JNIEnv *, jclass);

/*
 * Class:     com_questdb_std_Net
 * Method:    getEwouldblock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_questdb_std_Net_getEwouldblock
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
