/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nfsdb_misc_Os */

#ifndef _Included_com_nfsdb_misc_Os
#define _Included_com_nfsdb_misc_Os
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nfsdb_misc_Os_WINDOWS
#define com_nfsdb_misc_Os_WINDOWS 3L
#undef com_nfsdb_misc_Os__32Bit
#define com_nfsdb_misc_Os__32Bit -2L
#undef com_nfsdb_misc_Os_OSX
#define com_nfsdb_misc_Os_OSX 1L
#undef com_nfsdb_misc_Os_LINUX
#define com_nfsdb_misc_Os_LINUX 2L
#undef com_nfsdb_misc_Os_UNKNOWN
#define com_nfsdb_misc_Os_UNKNOWN -1L
/*
 * Class:     com_nfsdb_misc_Os
 * Method:    getPid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_nfsdb_misc_Os_getPid
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
