/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nfsdb_misc_Zip */

#ifndef _Included_com_nfsdb_misc_Zip
#define _Included_com_nfsdb_misc_Zip
#ifdef __cplusplus
extern "C" {
#endif
#undef com_nfsdb_misc_Zip_gzipHeaderLen
#define com_nfsdb_misc_Zip_gzipHeaderLen 10L
#undef com_nfsdb_misc_Zip_GZIP_MAGIC
#define com_nfsdb_misc_Zip_GZIP_MAGIC 35615L
/*
 * Class:     com_nfsdb_misc_Zip
 * Method:    deflateInit
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_com_nfsdb_misc_Zip_deflateInit
        (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_nfsdb_misc_Zip
 * Method:    setDeflateInput
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_com_nfsdb_misc_Zip_setDeflateInput
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_nfsdb_misc_Zip
 * Method:    deflate
 * Signature: (JJIZ)I
 */
JNIEXPORT jint JNICALL Java_com_nfsdb_misc_Zip_deflate
        (JNIEnv *, jclass, jlong, jlong, jint, jboolean);

/*
 * Class:     com_nfsdb_misc_Zip
 * Method:    deflateEnd
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nfsdb_misc_Zip_deflateEnd
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_nfsdb_misc_Zip
 * Method:    crc32
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_com_nfsdb_misc_Zip_crc32
        (JNIEnv *, jclass, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
