trigger:
  tags:
    include:
      - "*"
  branches:
    exclude:
      - "*"

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install awscli
      cd "$(Build.SourcesDirectory)"/pkg/ami/marketplace
      make build_release
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: eu-west-1
    displayName: "Deploy public image"
