trigger: none

pr: none

pool: hetzner-incus

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install awscli
      cd "$(Build.SourcesDirectory)"/pkg/ami/marketplace
      make install_aws_plugin
      make build_release
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_DEFAULT_REGION: eu-west-1
    displayName: "Deploy public image"
