trigger:
  tags:
    include:
      - 'patch/*'

pool:
  vmImage: 'ubuntu-20.04'
variables:
  tag: '$(Build.SourceBranchName)'

jobs:
  - job: RunOn
    displayName: "Build and push docker"

    pool:
      name: "Azure Pipelines"
      vmImage: "windows-latest"

    timeoutInMinutes: 60

    steps:
      - bash: |
          export hub_tag_name=$(git describe --tags | sed -e 's/^patch\///')  
          echo "##vso[task.setvariable variable=tag_name;isOutput=true]$tag_name"
        name: check_changes
        env:
          PRID: $(System.PullRequest.PullRequestNumber)
        displayName: "Check changed files"

      - task: Docker@2
        inputs:
          command: 'login'
          containerRegistry: quest_docker_hub

      - task: CmdLine@2
        displayName: Release Nightly MASTER
        inputs:
          script: |
            docker buildx build --platform linux/amd64,linux/arm64 --push -t questdb/questdb:nightly .
          workingDirectory: core
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

      - task: CmdLine@2
        displayName: Release Patch
        inputs:
          script: |
            docker buildx build --build-arg tag_name=$(tag) --platform linux/amd64,linux/arm64 --push -t questdb/questdb:$(hub_tag_name) .
          workingDirectory: core
        condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))