trigger:
  branches:
    include:
      - 'patch/*'

pool:
  vmImage: 'ubuntu-20.04'
variables:
  tag: '$(Build.SourceBranch)'
  tag_name: '$(Build.SourceBranchName)'

jobs:
  - job: RunOn
    displayName: "Build and push docker"

    pool:
      name: "Azure Pipelines"
      vmImage: "ubuntu-latest"

    timeoutInMinutes: 60

    steps:
      - bash: |
          export hub_tag_name=$(git describe --tags)-$(tag_name)  
          echo hub_tag_name=$hub_tag_name
          echo "##vso[task.setvariable variable=hub_tag_name]$hub_tag_name"
        name: check_changes
        displayName: "Check changed files"

      - task: Docker@2
        inputs:
          command: 'login'
          containerRegistry: quest_docker_hub

      - task: CmdLine@2
        displayName: Release Nightly MASTER
        inputs:
          script: |
            docker run --privileged --rm tonistiigi/binfmt --install arm64
            docker run --privileged --rm tonistiigi/binfmt
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 --push -t questdb/questdb:nightly .
          workingDirectory: core
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

      - task: CmdLine@2
        displayName: Release Patch
        inputs:
          script: |
            docker run --privileged --rm tonistiigi/binfmt --install arm64
            docker run --privileged --rm tonistiigi/binfmt
            docker buildx create --use
            export branch_name=$(echo $(tag) | sed -e 's/^refs\/heads\///')
            docker buildx build --build-arg tag_name=$branch_name --platform linux/amd64 --push -t questdb/questdb:$(hub_tag_name) .
          workingDirectory: core
        condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))