trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - '*.*.*'

pr: none

stages:
  - stage: BuildAndRunOnAzure
    displayName: "Building Binaires"
    jobs:
      - job: RunOn
        displayName: "on Azure workers"
        strategy:
          matrix:
            linux-jdk17:
              imageName: 'ubuntu-latest'
              poolName: "Azure Pipelines"
              os: Linux
              jdk: "1.17"
            windows:
              imageName: "windows-latest"
              poolName: "Azure Pipelines"
              os: macOS
              jdk: "1.17"
        pool:
          vmImage: $(imageName)
          name: $(poolName)
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: true
          - task: Maven@3
            displayName: "Building QuestDB"
            inputs:
              mavenPomFile: "core/pom.xml"
              goals: "package"
              options:
                "-DskipTests -Dhttp.keepAlive=false -P build-web-console,build-binaries"
              jdkVersionOption: $(jdk)
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(build.sourcesDirectory)/core/target'
              Contents: '$(build.sourcesDirectory)/core/target/questdb-*.gz'
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Release_Artifacts
    displayName: "Release binaries to github"
    dependsOn:
      - BuildAndRunOnAzure
    jobs:
      - job: Release
        pool:
          vmImage: 'ubuntu-latest'
        steps:

          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
              cleanDestinationFolder: true

          - script: |
              tag_name=$(echo "$(Build.SourceBranch)" | cut -d'/' -f '3-')
              echo "##vso[task.setvariable variable=TAG_NAME]${tag_name}"
              
              echo "Checking if release ${tag_name} already exists..."
              release_info=$(curl -H \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/questdb/questdb/releases/tags/${tag_name}" || true)
              
              if echo "$release_info" | grep -q 'Not Found'; then
                echo "Release does not exist."
                echo "##vso[task.setvariable variable=GITHUB_RELEASE_EXISTS]false"
              else
                echo "Release already exists."
                echo "##vso[task.setvariable variable=GITHUB_RELEASE_EXISTS]true"
              fi

          - task: GitHubRelease@1
            displayName: "Upload binaries to release"
            condition: and(succeeded(), eq(variables['GITHUB_RELEASE_EXISTS'], 'true'))
            inputs:
              gitHubConnection: 'ideoma'  # Replace with your GitHub service connection
              repositoryName: 'questdb/questdb'  # e.g., my-org/my-repo
              action: 'edit'
              assets: '$(Build.ArtifactStagingDirectory)/drop/*'

          - task: GitHubRelease@1
            displayName: "Create release"
            condition: and(succeeded(), eq(variables['GITHUB_RELEASE_EXISTS'], 'false'))
            inputs:
              gitHubConnection: 'ideoma'
              repositoryName: 'questdb/questdb'
              target: '$(Build.SourceVersion)'
              action: 'create'
              tagSource: 'userSpecifiedTag'
              tag: '$(TAG_NAME)'
              title: '$(TAG_NAME)'
              assets: '$(Build.ArtifactStagingDirectory)/drop/*'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
              isDraft: true

          - script: |
              sudo apt-get update
              sudo apt-get install awscli
              cd "$(Build.SourcesDirectory)"/pkg/ami/marketplace
              make install_aws_plugin
              make build_release
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
              AWS_DEFAULT_REGION: eu-west-1
            displayName: "AMI: Deploy public image"

