trigger: none

pr:
  branches:
    include:
      - master

variables:
  QDB_LOG_W_FILE_LOCATION: "$(Build.BinariesDirectory)"
  ARCHIVED_LOGS: "$(Build.ArtifactStagingDirectory)/questdb-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt).zip"
  CRASH_LOG_LOCATION: "$(Build.SourcesDirectory)/core/"
  ARCHIVED_GRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"

stages:
  - stage: RunTestsBranches
    displayName: "Running tests"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux:
              imageName: "ubuntu-latest"
              os: Linux
              jdk: "1.11"
            mac:
              imageName: "macos-latest"
              os: macOS
              jdk: "1.11"
            windows-cairo:
              imageName: "windows-latest"
              os: Windows
              jdk: "1.11"
              testSet: "cairo"
            windows-griffin:
              imageName: "windows-latest"
              os: Windows
              jdk: "1.11"
              testset: "griffin"
            linux-jdk8:
              imageName: "ubuntu-latest"
              os: Linux
              jdk: "1.8"
            linux-jdk17:
              imageName: "mac-latest"
              os: Linux
              jdk: "1.17"
        pool:
          vmImage: $(imageName)
        timeoutInMinutes: 30
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: false
          - task: Maven@3
            displayName: "Compile with Maven"
            inputs:
              mavenPomFile: "pom.xml"
              mavenOptions: "-Xmx3072m"
              options: "compile -DskipTests"
              jdkVersionOption: $(jdk)
          - task: Maven@3
            displayName: "Run tests with Maven"
            inputs:
              mavenPomFile: "core/pom.xml"
              mavenOptions: "-Xmx3072m"
              options:
                "--batch-mode --quiet
                -DquestdbLog=$(Build.SourcesDirectory)/ci/qlog.conf"
              jdkVersionOption: $(jdk)
          - task: ArchiveFiles@2
            displayName: "Tests failed -- Compress logs"
            condition: failed()
            inputs:
              rootFolderOrFile: $(QDB_LOG_W_FILE_LOCATION)
              includeRootFolder: false
              archiveFile: $(ARCHIVED_LOGS)
              quiet: true
          - task: PublishBuildArtifacts@1
            displayName: "Tests failed -- Upload logs"
            condition: failed()
            inputs:
              pathToPublish: $(ARCHIVED_LOGS)
              artifactName: MavenFailedTestsLogs
          - task: Bash@3
            displayName: "Tests failed -- rename crash dump"
            condition: failed()
            inputs:
              workingDirectory: $(CRASH_LOG_LOCATION)
              targetType: 'inline'
              script: find . -type f -name 'hs_*.log' -exec sh -c 'x="{}"; mv "$x" "$ARCHIVED_GRASH_LOG"' \;
            env:
              ARCHIVED_GRASH_LOG: $(ARCHIVED_GRASH_LOG)
          - task: PublishBuildArtifacts@1
            displayName: "Tests failed -- Upload crash logs"
            condition: failed()
            inputs:
              pathToPublish: $(ARCHIVED_GRASH_LOG)
              artifactName: MavenFailedTestsLogs
