trigger: none

pr: none

schedules:
  - cron: "*/15 * * * *"
    displayName: Run every 15 minutes
    branches:
      include:
        - master
    always: true

variables:
  QDB_LOG_W_FILE_LOCATION: "$(Build.BinariesDirectory)/tests.log"
  ARCHIVED_LOGS: "$(Build.ArtifactStagingDirectory)/questdb-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).zip"
  excludeTests: ""
  includeTests: "%regex[.*[^o].class]"
  MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
  MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m -XX:+UseParallelGC"
  MAVEN_RUN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Dmaven.resolver.transport=wagon -Dmaven.wagon.httpconnectionManager.ttlSeconds=30"
  MAVEN_VERSION: "version"
  MAVEN_VERSION_OPTION: "Default"

stages:
  - stage: HostedRunTestsBranches
    displayName: "Hosted Running tests"

    jobs:
      - job: RunOn
        workspace:
          clean: all
        displayName: "on"
        strategy:
          matrix:
            hetzner:
              os: Linux
              jdk: "1.17"
              testset: "all"
              includeTests: "%regex[.*Fuzz.*class]"
              javadoc_step: ""
              javadoc_profile: ""
        pool:
          name: hetzner-incus
        timeoutInMinutes: 60
        variables:
          SOURCE_CODE_CHANGED: true
          ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
        steps:
          - bash: |
              sudo apt-get update && sudo apt-get install -y openjdk-17-jdk maven build-essential zip
              JAVA_PATH="/usr/lib/jvm/java-17-openjdk-amd64"
              echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_PATH"
              echo "##vso[task.setvariable variable=JAVA_HOME_17_X64]$JAVA_PATH"
              echo "JAVA_HOME will be set to: $JAVA_PATH"
          - template: templates/steps.yml
