trigger: none

pr: none

schedules:
  - cron: "*/10 * * * *"
    displayName: Run every 15 minutes
    branches:
      include:
        - master
    always: true

variables:
  QDB_LOG_W_FILE_LOCATION: "$(Build.BinariesDirectory)/tests.log"
  ARCHIVED_LOGS: "$(Build.ArtifactStagingDirectory)/questdb-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).zip"
  excludeTests: ""
  includeTests: "%regex[.*[^o].class]"
  MAVEN_CACHE_FOLDER: $(HOME)/.m2/repository
  MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Xmx3072m"
  MAVEN_RUN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER) -Dmaven.resolver.transport=wagon -Dmaven.wagon.httpconnectionManager.ttlSeconds=30"
  MAVEN_VERSION: "version"
  MAVEN_VERSION_OPTION: "Default"

stages:
  - stage: HostedRunTestsBranches
    displayName: "Hosted Running tests"

    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            ubuntu-latest:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
              os: Linux
              jdk: "1.11"
              testset: "all"
              includeTests: "%regex[.*Fuzz.*class]"
              javadoc_step: ""
              javadoc_profile: ""
        pool:
          vmImage: $(imageName)
          name: $(poolName)
        timeoutInMinutes: 60
        variables:
          SOURCE_CODE_CHANGED: true
          ARCHIVED_CRASH_LOG: "$(Build.ArtifactStagingDirectory)/questdb-crash-$(Build.SourceBranchName)-$(Build.SourceVersion)-$(System.StageAttempt)-$(Agent.OS)-$(jdk).log"
        steps:
          - template: templates/steps.yml
            # run fuzz tests multiple times, x2 per job
          - template: templates/tests.yml
