/*+*****************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.test.griffin.fuzz;

import io.questdb.cairo.CairoEngine;
import io.questdb.cairo.CairoException;
import io.questdb.cairo.CursorPrinter;
import io.questdb.cairo.ImplicitCastException;
import io.questdb.cairo.sql.Record;
import io.questdb.cairo.sql.RecordCursor;
import io.questdb.cairo.sql.RecordCursorFactory;
import io.questdb.cairo.sql.RecordMetadata;
import io.questdb.griffin.SqlException;
import io.questdb.griffin.SqlExecutionContext;
import io.questdb.std.NumericException;
import io.questdb.std.str.StringSink;

/**
 * Runs one generated query, materializes every value, and decides whether
 * a thrown exception is acceptable. The oracle is crash-only:
 * <ul>
 *   <li>{@link SqlException} &rarr; accepted (parser, compiler and
 *       type-system errors such as "cannot compare X with Y");</li>
 *   <li>{@link ImplicitCastException} &rarr; accepted (runtime cast
 *       failures for out-of-range literals);</li>
 *   <li>{@link NumericException} &rarr; accepted (parse failures for
 *       numeric strings);</li>
 *   <li>anything else, including any {@link CairoException} &rarr;
 *       reported as a failure. Queries generated by this fuzzer should
 *       never leak a CairoException; if one escapes, the engine is
 *       surfacing an internal error through the query API.</li>
 * </ul>
 * "Materialize every value" means we call a per-column accessor for every
 * row via {@link CursorPrinter#printColumn}, which exercises the type's
 * read path end to end.
 */
public final class QueryRunner {
    private final CairoEngine engine;
    private final SqlExecutionContext executionContext;
    private final StringSink rowSink = new StringSink();

    public QueryRunner(CairoEngine engine, SqlExecutionContext executionContext) {
        this.engine = engine;
        this.executionContext = executionContext;
    }

    public Result run(String sql) {
        try (RecordCursorFactory factory = engine.select(sql, executionContext)) {
            try (RecordCursor cursor = factory.getCursor(executionContext)) {
                RecordMetadata metadata = factory.getMetadata();
                int columnCount = metadata.getColumnCount();
                Record record = cursor.getRecord();
                int rowsRead = 0;
                while (cursor.hasNext()) {
                    rowSink.clear();
                    for (int i = 0; i < columnCount; i++) {
                        CursorPrinter.printColumn(record, metadata, i, rowSink, false);
                        rowSink.put('\t');
                    }
                    rowsRead++;
                }
                return Result.ok(rowsRead);
            }
        } catch (SqlException e) {
            return Result.skipped(e.getFlyweightMessage().toString());
        } catch (ImplicitCastException e) {
            return Result.skipped(e.getFlyweightMessage().toString());
        } catch (NumericException e) {
            return Result.skipped("NumericException");
        } catch (Throwable t) {
            return Result.failed(sql, t);
        }
    }

    public static final class Result {
        private final Throwable failure;
        private final int rowsRead;
        private final String skipReason;
        private final String sql;
        private final State state;

        private Result(State state, int rowsRead, String skipReason, String sql, Throwable failure) {
            this.state = state;
            this.rowsRead = rowsRead;
            this.skipReason = skipReason;
            this.sql = sql;
            this.failure = failure;
        }

        public static Result failed(String sql, Throwable t) {
            return new Result(State.FAILED, 0, null, sql, t);
        }

        public static Result ok(int rowsRead) {
            return new Result(State.OK, rowsRead, null, null, null);
        }

        public static Result skipped(String reason) {
            return new Result(State.SKIPPED, 0, reason, null, null);
        }

        public Throwable getFailure() {
            return failure;
        }

        public int getRowsRead() {
            return rowsRead;
        }

        public String getSkipReason() {
            return skipReason;
        }

        public String getSql() {
            return sql;
        }

        public boolean isFailed() {
            return state == State.FAILED;
        }

        public boolean isSkipped() {
            return state == State.SKIPPED;
        }

        private enum State {OK, SKIPPED, FAILED}
    }
}
