/*+*****************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.test.griffin.fuzz;

import io.questdb.cairo.CairoEngine;
import io.questdb.cairo.CairoException;
import io.questdb.cairo.CursorPrinter;
import io.questdb.cairo.ImplicitCastException;
import io.questdb.cairo.SqlJitMode;
import io.questdb.cairo.sql.BindVariableService;
import io.questdb.cairo.sql.Record;
import io.questdb.cairo.sql.RecordCursor;
import io.questdb.cairo.sql.RecordCursorFactory;
import io.questdb.cairo.sql.RecordMetadata;
import io.questdb.griffin.SqlException;
import io.questdb.griffin.SqlExecutionContext;
import io.questdb.griffin.TextPlanSink;
import io.questdb.std.Chars;
import io.questdb.std.NumericException;
import io.questdb.std.ObjList;
import io.questdb.std.str.StringSink;
import io.questdb.test.griffin.fuzz.FuzzTableFactory.ParquetMode;

import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Runs one generated query, materializes every value, and decides whether
 * a thrown exception is acceptable. The oracle is crash-only:
 * <ul>
 *   <li>{@link SqlException} &rarr; accepted (parser, compiler and
 *       type-system errors such as "cannot compare X with Y");</li>
 *   <li>{@link ImplicitCastException} &rarr; accepted (runtime cast
 *       failures for out-of-range literals);</li>
 *   <li>{@link NumericException} &rarr; accepted (parse failures for
 *       numeric strings);</li>
 *   <li>anything else, including any {@link CairoException} &rarr;
 *       reported as a failure. Queries generated by this fuzzer should
 *       never leak a CairoException; if one escapes, the engine is
 *       surfacing an internal error through the query API.</li>
 * </ul>
 * "Materialize every value" means we call a per-column accessor for every
 * row via {@link CursorPrinter#printColumn}, which exercises the type's
 * read path end to end.
 * <p>
 * Differential modes:
 * <ul>
 *   <li>{@code diffJit} runs the same SQL on the primary table twice
 *       &mdash; once with {@link SqlJitMode#JIT_MODE_ENABLED}, once with
 *       {@link SqlJitMode#JIT_MODE_DISABLED} &mdash; and compares the
 *       two materializations. Catches JIT vs. Java-filter divergences.</li>
 *   <li>{@code diffShadow} rewrites the SQL to read from the shadow
 *       sibling (same data, independently random parquet/index settings)
 *       and compares the two materializations at JIT-off. Catches
 *       silent storage divergences across native/parquet partitions and
 *       across indexed/non-indexed symbol columns.</li>
 * </ul>
 * The two modes share a pivot: {@code primary @ JIT-off}. With both
 * enabled, three runs per query are required (primary @ JIT-on,
 * primary @ JIT-off, shadow @ JIT-off); the JIT diff compares the first
 * two, the storage diff compares the second and third. Either divergence
 * fails the query, and the failure message names the axis.
 * <p>
 * Row-set comparison is a multiset (line-sorted) so parallel iteration
 * order does not produce false positives. {@code deterministic=false}
 * queries (LIMIT over parallel GROUP BY / hash join etc.) compare row
 * counts only.
 * <p>
 * Two storage-diff escape valves keep the oracle focused on data
 * correctness rather than planner artifacts:
 * <ul>
 *   <li>If both sides throw the same allowlisted exception class (even
 *       with different messages), the query was rejected by both paths
 *       and treated as skip. Index/parquet differences can change which
 *       sub-expression the compiler reports first.</li>
 *   <li>If exactly one side throws a known planner-sensitivity error
 *       (currently the time-series-join ASC-timestamp check), the diff
 *       is treated as skip. That check inspects cursor metadata that
 *       legitimately differs between an indexed-symbol lookup (loses
 *       TS-ASC) and a full scan (preserves it).</li>
 * </ul>
 */
public final class QueryRunner {
    private final boolean diffJit;
    private final boolean diffShadow;
    private final CairoEngine engine;
    private final SqlExecutionContext executionContext;
    private final TextPlanSink planSink = new TextPlanSink();
    private final boolean primaryHasAnyParquet;
    private final Pattern[] primaryPatterns;
    private final StringSink rowsA = new StringSink();
    private final StringSink rowsB = new StringSink();
    private final StringSink rowsC = new StringSink();
    private final StringSink rowsD = new StringSink();
    private final boolean shadowHasAnyParquet;
    private final String[] shadowReplacements;

    public QueryRunner(
            CairoEngine engine,
            SqlExecutionContext executionContext,
            boolean diffJit,
            boolean diffShadow,
            ObjList<FuzzTable> tables
    ) {
        this.engine = engine;
        this.executionContext = executionContext;
        this.diffJit = diffJit;
        this.diffShadow = diffShadow;
        if (diffShadow) {
            int n = tables.size();
            primaryPatterns = new Pattern[n];
            shadowReplacements = new String[n];
            boolean primaryParquet = false;
            boolean shadowParquet = false;
            for (int i = 0; i < n; i++) {
                FuzzTable t = tables.getQuick(i);
                FuzzTable shadow = t.getShadow();
                if (shadow == null) {
                    throw new IllegalArgumentException("diffShadow requires every table to have a shadow sibling: " + t.getName());
                }
                primaryPatterns[i] = Pattern.compile("\\b" + Pattern.quote(t.getName()) + "\\b");
                shadowReplacements[i] = Matcher.quoteReplacement(shadow.getName());
                primaryParquet |= t.getParquetMode() != ParquetMode.NONE;
                shadowParquet |= shadow.getParquetMode() != ParquetMode.NONE;
            }
            primaryHasAnyParquet = primaryParquet;
            shadowHasAnyParquet = shadowParquet;
        } else {
            primaryPatterns = null;
            shadowReplacements = null;
            primaryHasAnyParquet = false;
            shadowHasAnyParquet = false;
        }
    }

    public Result run(GeneratedQuery query) {
        String sql = query.sql();
        if (!diffJit && !diffShadow && !query.hasBind()) {
            Outcome outcome = runOnce(sql, rowsA, primaryHasAnyParquet);
            return toResult(sql, outcome);
        }
        int prevJitMode = executionContext.getJitMode();
        try {
            // Pivot: primary at JIT-off. The pivot is the right-hand side of
            // the JIT comparison and the left-hand side of the storage and
            // bind-variable comparisons, so it runs whenever any of the three
            // diffs is on.
            executionContext.setJitMode(SqlJitMode.JIT_MODE_DISABLED);
            Outcome bJ = runOnce(sql, rowsB, primaryHasAnyParquet);

            Outcome aJ = null;
            Result jitResult = null;
            if (diffJit) {
                executionContext.setJitMode(SqlJitMode.JIT_MODE_ENABLED);
                aJ = runOnce(sql, rowsA, primaryHasAnyParquet);
                jitResult = reconcilePair(sql, aJ, bJ, rowsA, rowsB, query.deterministic(),
                        "JIT divergence", "jit on ", "jit off");
                if (jitResult.isFailed()) {
                    return jitResult;
                }
            }

            if (diffShadow) {
                executionContext.setJitMode(SqlJitMode.JIT_MODE_DISABLED);
                String shadowSql = rewriteForShadow(sql);
                Outcome bS = runOnce(shadowSql, rowsC, shadowHasAnyParquet);
                Result storageResult = reconcilePair(
                        sql,
                        bJ,
                        bS,
                        rowsB,
                        rowsC,
                        query.deterministic(),
                        "storage divergence",
                        "primary",
                        "shadow "
                );
                if (storageResult.isFailed()) {
                    return storageResult;
                }
            }

            if (query.hasBind()) {
                Result bindResult = runBindVariant(query, aJ, bJ);
                if (bindResult != null && bindResult.isFailed()) {
                    return bindResult;
                }
            }

            return jitResult != null ? jitResult : Result.ok();
        } finally {
            executionContext.setJitMode(prevJitMode);
        }
    }

    /**
     * Runs the bind-variable form of the query and reconciles it against the
     * literal form's pivots. Bind variables are set via {@code setStr} keyed
     * by name (the {@code :bN} placeholders generated by
     * {@link io.questdb.test.griffin.fuzz.expr.BindContext}), so QuestDB's
     * normal bind-to-typed coercion is exercised end to end. The bind form
     * runs at JIT-off (compared to {@code bJ}) and, when diff-JIT is enabled,
     * also at JIT-on (compared to {@code aJ}) since the JIT compiler has its
     * own bind-variable handling that doesn't share code with the
     * Java-filter path. Returns null when both comparisons are benign;
     * otherwise returns a Result describing the divergence.
     */
    private Result runBindVariant(GeneratedQuery query, Outcome aJ, Outcome bJ) {
        BindVariableService bvs = executionContext.getBindVariableService();
        ObjList<String> names = query.bindNames();
        ObjList<String> values = query.bindValues();
        try {
            bvs.clear();
            for (int i = 0, n = values.size(); i < n; i++) {
                bvs.setStr(names.getQuick(i), values.getQuick(i));
            }
        } catch (SqlException e) {
            // Setter rejected the value (rare; e.g. malformed UTF-8). Treat as
            // skip: the bind path is not the thing under test for this kind
            // of failure.
            bvs.clear();
            return Result.skipped("bind setter rejected value: " + e.getFlyweightMessage());
        }
        try {
            executionContext.setJitMode(SqlJitMode.JIT_MODE_DISABLED);
            Outcome bindOff = runOnce(query.bindSql(), rowsD, primaryHasAnyParquet);
            Result offResult = reconcilePair(
                    query.sql(),
                    bJ,
                    bindOff,
                    rowsB,
                    rowsD,
                    query.deterministic(),
                    "bind variable divergence (jit off)",
                    "literal",
                    "bind   "
            );
            if (offResult.isFailed()) {
                return offResult;
            }
            if (aJ != null) {
                executionContext.setJitMode(SqlJitMode.JIT_MODE_ENABLED);
                Outcome bindOn = runOnce(query.bindSql(), rowsD, primaryHasAnyParquet);
                return reconcilePair(
                        query.sql(),
                        aJ,
                        bindOn,
                        rowsA,
                        rowsD,
                        query.deterministic(),
                        "bind variable divergence (jit on)",
                        "literal",
                        "bind   "
                );
            }
            return offResult;
        } finally {
            bvs.clear();
        }
    }

    private static boolean isAcceptedSkip(Throwable t) {
        return t instanceof SqlException || t instanceof ImplicitCastException || t instanceof NumericException;
    }

    /**
     * One outcome threw an allowlisted cast/numeric error, the other succeeded.
     * Without checking row count or access path. Caller restricts when to apply
     * this -- see the bind-axis use site for rationale.
     */
    private static boolean isFoldOrderAsymmetry(Outcome a, Outcome b) {
        Outcome erroring = a.failure != null ? a : b;
        Outcome succeeding = a.failure != null ? b : a;
        if (erroring.failure == null || succeeding.failure != null) {
            return false;
        }
        return erroring.failure instanceof ImplicitCastException
                || erroring.failure instanceof NumericException;
    }

    /**
     * Erroring side threw a per-row runtime cast or numeric overflow,
     * succeeding side reached the index-driven access path. An index probe
     * filters rows out before they reach the residual filter, so a row that
     * would have triggered the cast or overflow on the full-scan side never
     * makes it to the comparator on the indexed side. The asymmetry is a
     * planner choice driven by the table's index configuration, not a data
     * divergence.
     */
    private static boolean isIndexFilteredAsymmetry(Outcome erroring, Outcome succeeding) {
        if (succeeding.failure != null || !succeeding.hasIndex) {
            return false;
        }
        return erroring.failure instanceof NumericException
                || erroring.failure instanceof ImplicitCastException;
    }

    /**
     * Erroring side threw a per-row runtime cast or numeric overflow,
     * succeeding side ran against tables with parquet partitions. Parquet
     * pushdown evaluates predicates against row-group statistics and
     * column dictionaries before materializing rows, so an out-of-range
     * cast or scale-alignment overflow that the full-scan side would hit
     * may simply not be reached on the parquet side. The asymmetry is a
     * planner choice driven by the table's storage format, not a data
     * divergence.
     */
    private static boolean isParquetFilteredAsymmetry(Outcome erroring, Outcome succeeding) {
        if (succeeding.failure != null || !succeeding.usesParquet) {
            return false;
        }
        return erroring.failure instanceof NumericException
                || erroring.failure instanceof ImplicitCastException;
    }

    /**
     * One side threw a known planner-sensitivity error. These are structural
     * compile-time checks whose outcome depends on the access path the
     * planner picks, which in turn depends on index/parquet configuration
     * or whether a sub-expression survives constant folding.
     * <ul>
     *   <li>"doesn't have ASC timestamp order" - time-series-join check that
     *       inspects cursor metadata; an indexed-symbol lookup loses TS-ASC
     *       where a full scan preserves it, so primary and shadow legitimately
     *       differ.</li>
     *   <li>"column must appear in GROUP BY clause" - the literal form
     *       constant-folds a sub-expression so its repeated occurrence in
     *       projection and GROUP BY becomes the same constant; the bind
     *       form keeps the bind variable opaque and the planner's
     *       expression-equivalence check rejects the GROUP BY because
     *       it cannot see the two occurrences as the same expression.</li>
     *   <li>"constant expected" - a GROUP BY / SAMPLE BY position that
     *       requires a compile-time constant accepts the literal but
     *       rejects the bind variable, since {@code :bN} is not foldable
     *       at compile time.</li>
     *   <li>"there is no matching function" - the literal form types its
     *       constant at compile time (e.g. {@code count_distinct(true)}
     *       resolves to BOOLEAN, for which no overload exists), while the
     *       bind form's value is supplied through {@code setStr} so the
     *       function lookup picks the STRING overload instead. The
     *       function-lookup table is a planner-controlled choice driven by
     *       compile-time vs. bind-time type information, not a data
     *       divergence.</li>
     *   <li>"decimal places but scale is limited to" - {@code FunctionParser}
     *       routes a literal {@code DOUBLE/FLOAT::DECIMAL(p,s)} through
     *       {@code DecimalUtil.parseDecimalConstant} with the strict {@code
     *       DecimalParser.parse(..., lossy=false)} so that an over-scaled
     *       constant is rejected at compile time to avoid silent precision
     *       loss. The bind form runs the value through
     *       {@code CastDoubleToDecimalFunctionFactory} which calls {@code
     *       Numbers.doubleToDecimal(d, ..., lossy=true)} and silently
     *       truncates excess decimal places. Same SQL, different policies on
     *       the literal vs. runtime path; not a data divergence.</li>
     * </ul>
     */
    private static boolean isPlannerSensitivityAsymmetry(Outcome o) {
        if (!(o.failure instanceof SqlException)) {
            return false;
        }
        return o.exceptionMessage.contains("doesn't have ASC timestamp order")
                || o.exceptionMessage.contains("column must appear in GROUP BY clause")
                || o.exceptionMessage.contains("constant expected")
                || o.exceptionMessage.contains("there is no matching function")
                || o.exceptionMessage.contains("decimal places but scale is limited to");
    }

    /**
     * Detects whether a rendered plan uses an index-driven access path.
     * Markers come from the {@code sink.type(...)} calls in QuestDB's
     * cursor factories: "Index forward scan" / "Index backward scan",
     * "Async index backward scan", "AsOf Join Indexed Scan",
     * "SortedSymbolIndex", "LatestByAllIndexed". These are the operators
     * that probe a bitmap index instead of scanning every page frame
     * row, so a per-row cast or numeric error on an out-of-range value
     * may legitimately not surface here even though the equivalent
     * full-scan path on a sibling table throws.
     */
    private static boolean planUsesIndex(CharSequence plan) {
        int n = plan.length();
        return Chars.indexOf(plan, 0, n, "Index ") >= 0
                || Chars.indexOf(plan, 0, n, "Indexed") >= 0
                || Chars.indexOf(plan, 0, n, "SortedSymbolIndex") >= 0
                || Chars.indexOf(plan, 0, n, "Async index") >= 0;
    }

    private static String renderOutcome(Outcome outcome, CharSequence rows) {
        if (outcome.failure == null) {
            return "ok, " + outcome.rowsRead + " rows:\n" + rows;
        }
        return outcome.exceptionClass + ": " + outcome.exceptionMessage;
    }

    /**
     * Returns true iff every cell in {@code a} either matches the
     * corresponding cell in {@code b} exactly or both parse as finite
     * doubles within a small relative tolerance. Used as a fallback for
     * floating-point aggregates whose last-digit value depends on the
     * order of summation, which legitimately differs between an indexed
     * scan and a full scan or between parquet and native partitions.
     */
    private static boolean rowEqualsWithFpTolerance(String a, String b) {
        if (a.equals(b)) {
            return true;
        }
        String[] tokensA = a.split("\t", -1);
        String[] tokensB = b.split("\t", -1);
        if (tokensA.length != tokensB.length) {
            return false;
        }
        for (int i = 0; i < tokensA.length; i++) {
            if (tokensA[i].equals(tokensB[i])) {
                continue;
            }
            double da;
            double db;
            try {
                da = Double.parseDouble(tokensA[i]);
                db = Double.parseDouble(tokensB[i]);
            } catch (NumberFormatException e) {
                return false;
            }
            if (!Double.isFinite(da) || !Double.isFinite(db)) {
                return false;
            }
            // 1e-12 relative is loose enough for DOUBLE reduction-order drift
            // and tight enough to flag a real arithmetic divergence; the
            // 1e-15 floor handles values near zero where relative error
            // is ill-defined.
            double scale = Math.max(Math.abs(da), Math.abs(db));
            double doubleEps = Math.max(1e-15, scale * 1e-12);
            if (Math.abs(da - db) <= doubleEps) {
                continue;
            }
            // Parallel SUM/AVG over FLOAT (or DOUBLE columns whose values
            // were promoted from FLOAT) drifts at single-precision ulps
            // when partial sums are merged across worker threads, which
            // is several orders of magnitude looser than 1e-12 relative.
            // Allow up to 32 FLOAT ulps -- still tight enough to flag a
            // real arithmetic bug, which would shift the result by far
            // more than ulp-scale noise.
            double floatEps = Math.max(1e-15, Math.ulp((float) scale) * 32.0);
            if (Math.abs(da - db) > floatEps) {
                return false;
            }
        }
        return true;
    }

    /**
     * Multiset comparison: the two row sets are equal iff they contain the same
     * lines, regardless of order. Parallel operators (GROUP BY, etc.) do not
     * guarantee a stable iteration order across runs, but neither toggle
     * affects which rows are produced -- only the per-row evaluation. So
     * order divergence is normal; element-set divergence is a real bug.
     */
    private static boolean rowsetEquals(StringSink a, StringSink b) {
        // Fast path: identical text.
        if (a.length() == b.length() && a.toString().contentEquals(b)) {
            return true;
        }
        String[] linesA = a.toString().split("\n", -1);
        String[] linesB = b.toString().split("\n", -1);
        if (linesA.length != linesB.length) {
            return false;
        }
        Arrays.sort(linesA);
        Arrays.sort(linesB);
        for (int i = 0; i < linesA.length; i++) {
            if (!linesA[i].equals(linesB[i])) {
                return false;
            }
        }
        return true;
    }

    /**
     * Multiset comparison with floating-point tolerance: the two row sets
     * are equivalent iff each line in {@code a} can be paired with a
     * distinct line in {@code b} that matches under
     * {@link #rowEqualsWithFpTolerance(String, String)}. Used after a
     * strict {@link #rowsetEquals} fails to absorb FP-reduction-order
     * drift in {@code SUM}/{@code AVG} aggregates whose last digits depend
     * on the access path the planner picks. Greedy matching is O(n^2);
     * fuzz queries produce small row sets so this is fine.
     */
    private static boolean rowsetEqualsWithFpTolerance(StringSink a, StringSink b) {
        String[] linesA = a.toString().split("\n", -1);
        String[] linesB = b.toString().split("\n", -1);
        if (linesA.length != linesB.length) {
            return false;
        }
        boolean[] usedB = new boolean[linesB.length];
        for (String lineA : linesA) {
            boolean matched = false;
            for (int j = 0; j < linesB.length; j++) {
                if (!usedB[j] && rowEqualsWithFpTolerance(lineA, linesB[j])) {
                    usedB[j] = true;
                    matched = true;
                    break;
                }
            }
            if (!matched) {
                return false;
            }
        }
        return true;
    }

    private static Result toResult(String sql, Outcome outcome) {
        if (outcome.failure == null) {
            return Result.ok();
        }
        if (isAcceptedSkip(outcome.failure)) {
            return Result.skipped(outcome.exceptionClass + ": " + outcome.exceptionMessage);
        }
        return Result.failed(sql, outcome.failure);
    }

    private AssertionError divergence(String diffName, Outcome a, Outcome b,
                                      CharSequence rowsA, CharSequence rowsB,
                                      String labelA, String labelB) {
        String msg = diffName + ":\n"
                + "  " + labelA + ": " + renderOutcome(a, rowsA) + "\n"
                + "  " + labelB + ": " + renderOutcome(b, rowsB);
        Throwable cause = a.failure != null ? a.failure : b.failure;
        return cause == null ? new AssertionError(msg) : new AssertionError(msg, cause);
    }

    /**
     * Compares one outcome pair. Used for both the JIT axis (primary @ on vs
     * primary @ off) and the storage axis (primary vs shadow). The {@code
     * diffName} and {@code labelA}/{@code labelB} parameters only affect the
     * failure message; the comparison logic itself is identical -- both axes
     * must produce the same row multiset on a deterministic query, the same
     * row count on a non-deterministic query, and the same exception class
     * (modulo per-row message variance on non-deterministic queries) when
     * both throw.
     */
    private Result reconcilePair(String sql, Outcome a, Outcome b, StringSink rowsA, StringSink rowsB,
                                 boolean deterministic, String diffName, String labelA, String labelB) {
        // Both succeeded.
        if (a.failure == null && b.failure == null) {
            if (rowsetEquals(rowsA, rowsB)) {
                return Result.ok();
            }
            // Non-deterministic queries (LIMIT without fully-disambiguating
            // ORDER BY over parallel GROUP BY / hash join, etc.) can return a
            // different valid subset of rows on each run. Row content diff is
            // meaningless for them, but a row count diff is still a real bug:
            // the two paths must agree on how many rows survive the LIMIT,
            // regardless of which rows they are.
            if (!deterministic && a.rowsRead == b.rowsRead) {
                return Result.ok();
            }
            // Both sides agree on the row set up to floating-point
            // last-digit drift. SUM/AVG over DOUBLE/FLOAT is sensitive to
            // the order of summation, which legitimately differs across
            // index/parquet access paths and across JIT modes. The
            // tolerance is tight enough to flag a real arithmetic
            // divergence while absorbing reduction-order noise.
            if (a.rowsRead == b.rowsRead && rowsetEqualsWithFpTolerance(rowsA, rowsB)) {
                return Result.skipped("rowset matches with floating-point tolerance");
            }
            return Result.failed(sql, divergence(diffName, a, b, rowsA, rowsB, labelA, labelB));
        }
        // Both threw the same exception. Outcome the same way the single-run
        // path would: skip if allowlisted, fail if not.
        if (a.failure != null && b.failure != null
                && a.exceptionClass.equals(b.exceptionClass)
                && a.exceptionMessage.equals(b.exceptionMessage)) {
            if (isAcceptedSkip(a.failure)) {
                return Result.skipped(a.exceptionClass + ": " + a.exceptionMessage);
            }
            return Result.failed(sql, a.failure);
        }
        // Both threw allowlisted exceptions but the messages, and possibly
        // the classes, differ. For a non-deterministic query, a per-row
        // cast/numeric exception fires on whichever row the iterator visits
        // first, and parallel GROUP BY / hash join paths can return rows in
        // different orders across runs. For a deterministic query under the
        // storage diff, the two paths can hit different first errors because
        // index/parquet settings change which sub-expression the planner
        // evaluates first: one side may reject a DECIMAL literal at compile
        // time (SqlException) while the other compiles and hits a per-row
        // IPv4 cast at runtime (ImplicitCastException). In all such cases
        // both paths reject the query, only the stage and the error class
        // differ, so treat as skip.
        if (isAcceptedSkip(a.failure) && isAcceptedSkip(b.failure)) {
            if (a.exceptionClass.equals(b.exceptionClass)) {
                return Result.skipped(a.exceptionClass + ": (varies)");
            }
            return Result.skipped(a.exceptionClass + " vs " + b.exceptionClass);
        }
        // One side threw a known planner-sensitivity error and the other
        // accepted the query. The error is a structural check that depends
        // on cursor metadata (e.g. whether the access path preserves
        // timestamp order), and that metadata can legitimately differ when
        // primary and shadow have different index/parquet configurations:
        // an indexed-symbol predicate uses an index lookup that loses TS
        // ordering, while a non-indexed scan preserves it. Skip rather than
        // flag, since the diff is a planner choice, not a data divergence.
        if (isPlannerSensitivityAsymmetry(a) || isPlannerSensitivityAsymmetry(b)) {
            return Result.skipped("planner sensitivity asymmetry");
        }
        // One side threw a per-row runtime error (NumericException for
        // overflow during scale alignment, ImplicitCastException for an
        // out-of-range cast) and the other side succeeded with an
        // index-driven access path. An index probe filters rows out
        // before they reach the residual filter, so the offending row
        // simply never reaches the comparator/cast on the indexed side.
        // Whether a row triggers the throw is therefore a planner choice
        // determined by the side's access path, not a data divergence.
        final String exceptionClass = a.failure != null ? a.exceptionClass : b.exceptionClass;
        if (isIndexFilteredAsymmetry(a, b) || isIndexFilteredAsymmetry(b, a)) {
            return Result.skipped("index-filtered " + exceptionClass);
        }
        // Same shape as the index-filtered rule but for parquet. The
        // succeeding side accessed tables with parquet partitions and the
        // parquet read path can prune rows via row-group statistics or
        // dictionaries before the comparator runs, so the offending value
        // never reaches the residual filter.
        if (isParquetFilteredAsymmetry(a, b) || isParquetFilteredAsymmetry(b, a)) {
            return Result.skipped("parquet-filtered " + exceptionClass);
        }
        // One side returned an empty result, the other threw an allowlisted
        // cast/numeric error. The succeeding side's WHERE was statically
        // satisfiable-as-empty (e.g. WhereClauseParser folded a contradiction
        // like 'c IS NOT NULL AND c IS NULL' to FALSE), so its compiler short
        // -circuited before reaching a constant subtree that contains an
        // out-of-range cast literal. The erroring side's compiler reached
        // that subtree and threw on the constant fold. Both sides agree the
        // query has zero valid rows; the diff is purely planner-fold-order,
        // not a data divergence.
        if (isUnsatisfiableShortCircuitAsymmetry(a, b) || isUnsatisfiableShortCircuitAsymmetry(b, a)) {
            return Result.skipped("unsatisfiable-shortcircuit " + exceptionClass);
        }
        // Same fold-order asymmetry as above, but on the bind axis where the
        // two sides are guaranteed semantically identical (literal vs the same
        // value bound as a parameter). The factory for the bound form takes
        // the runtime-constant branch, which defers cast decoding to init();
        // the optimizer can then elide the offending subtree (e.g. when it
        // sits behind an OR with a tautology) before init() ever runs. The
        // literal form has no such defer and throws on the constant fold.
        // Both forms agree on the query semantics; only the fold order of an
        // elidable constant subtree differs.
        if (diffName.contains("bind variable") && isFoldOrderAsymmetry(a, b)) {
            return Result.skipped("bind-fold-order " + exceptionClass);
        }
        // Anything else: divergence (one succeeded, one threw a non-skip
        // error; or both threw different exception classes).
        return Result.failed(sql, divergence(diffName, a, b, rowsA, rowsB, labelA, labelB));
    }

    private static boolean isUnsatisfiableShortCircuitAsymmetry(Outcome erroring, Outcome succeeding) {
        if (succeeding.failure != null || succeeding.rowsRead != 0) {
            return false;
        }
        return erroring.failure instanceof ImplicitCastException
                || erroring.failure instanceof NumericException;
    }

    private String rewriteForShadow(String sql) {
        String result = sql;
        for (int i = 0; i < primaryPatterns.length; i++) {
            result = primaryPatterns[i].matcher(result).replaceAll(shadowReplacements[i]);
        }
        return result;
    }

    private Outcome runOnce(String sql, StringSink rows, boolean usesParquet) {
        rows.clear();
        try (RecordCursorFactory factory = engine.select(sql, executionContext)) {
            int rowsRead;
            try (RecordCursor cursor = factory.getCursor(executionContext)) {
                RecordMetadata metadata = factory.getMetadata();
                int columnCount = metadata.getColumnCount();
                Record record = cursor.getRecord();
                rowsRead = 0;
                while (cursor.hasNext()) {
                    for (int i = 0; i < columnCount; i++) {
                        CursorPrinter.printColumn(record, metadata, i, rows, false);
                        rows.put('\t');
                    }
                    rows.put('\n');
                    rowsRead++;
                }
            }
            planSink.of(factory, executionContext);
            return Outcome.ok(rowsRead, planUsesIndex(planSink.getSink()), usesParquet);
        } catch (SqlException e) {
            return Outcome.error(e, e.getFlyweightMessage().toString(), usesParquet);
        } catch (ImplicitCastException e) {
            return Outcome.error(e, e.getFlyweightMessage().toString(), usesParquet);
        } catch (NumericException e) {
            return Outcome.error(e, "", usesParquet);
        } catch (Throwable t) {
            String msg = t.getMessage();
            return Outcome.error(t, msg == null ? "" : msg, usesParquet);
        }
    }

    private record Outcome(
            int rowsRead,
            boolean hasIndex,
            boolean usesParquet,
            Throwable failure,
            String exceptionClass,
            String exceptionMessage
    ) {

        static Outcome error(Throwable t, String message, boolean usesParquet) {
            return new Outcome(0, false, usesParquet, t, t.getClass().getSimpleName(), message);
        }

        static Outcome ok(int rowsRead, boolean hasIndex, boolean usesParquet) {
            return new Outcome(rowsRead, hasIndex, usesParquet, null, null, null);
        }
    }

    public static final class Result {
        private final Throwable failure;
        private final String skipReason;
        private final String sql;
        private final State state;

        private Result(State state, String skipReason, String sql, Throwable failure) {
            this.state = state;
            this.skipReason = skipReason;
            this.sql = sql;
            this.failure = failure;
        }

        public static Result failed(String sql, Throwable t) {
            return new Result(State.FAILED, null, sql, t);
        }

        public static Result ok() {
            return new Result(State.OK, null, null, null);
        }

        public static Result skipped(String reason) {
            return new Result(State.SKIPPED, reason, null, null);
        }

        public Throwable getFailure() {
            return failure;
        }

        public String getSkipReason() {
            return skipReason;
        }

        public String getSql() {
            return sql;
        }

        public boolean isFailed() {
            return state == State.FAILED;
        }

        public boolean isSkipped() {
            return state == State.SKIPPED;
        }

        private enum State {OK, SKIPPED, FAILED}
    }
}
