/*+*****************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2026 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.test.griffin.fuzz;

import io.questdb.cairo.CairoEngine;
import io.questdb.cairo.CairoException;
import io.questdb.cairo.CursorPrinter;
import io.questdb.cairo.ImplicitCastException;
import io.questdb.cairo.SqlJitMode;
import io.questdb.cairo.sql.Record;
import io.questdb.cairo.sql.RecordCursor;
import io.questdb.cairo.sql.RecordCursorFactory;
import io.questdb.cairo.sql.RecordMetadata;
import io.questdb.griffin.SqlException;
import io.questdb.griffin.SqlExecutionContext;
import io.questdb.std.Chars;
import io.questdb.std.NumericException;
import io.questdb.std.str.StringSink;

/**
 * Runs one generated query, materializes every value, and decides whether
 * a thrown exception is acceptable. The oracle is crash-only:
 * <ul>
 *   <li>{@link SqlException} &rarr; accepted (parser, compiler and
 *       type-system errors such as "cannot compare X with Y");</li>
 *   <li>{@link ImplicitCastException} &rarr; accepted (runtime cast
 *       failures for out-of-range literals);</li>
 *   <li>{@link NumericException} &rarr; accepted (parse failures for
 *       numeric strings);</li>
 *   <li>anything else, including any {@link CairoException} &rarr;
 *       reported as a failure. Queries generated by this fuzzer should
 *       never leak a CairoException; if one escapes, the engine is
 *       surfacing an internal error through the query API.</li>
 * </ul>
 * "Materialize every value" means we call a per-column accessor for every
 * row via {@link CursorPrinter#printColumn}, which exercises the type's
 * read path end to end.
 * <p>
 * When constructed with {@code diffJit = true}, every query is run twice
 * &mdash; once with {@link SqlJitMode#JIT_MODE_ENABLED} and once with
 * {@link SqlJitMode#JIT_MODE_DISABLED} &mdash; and the two materializations
 * are compared. Any divergence (different row text, different exception
 * class/message, or one path succeeding while the other throws) is reported
 * as a failure. Queries that do not engage the filter JIT path produce
 * identical output in both modes, so the toggle is safe to apply
 * universally; the price is roughly doubled run time per query.
 */
public final class QueryRunner {
    private final boolean diffJit;
    private final CairoEngine engine;
    private final SqlExecutionContext executionContext;
    private final StringSink rowsA = new StringSink();
    private final StringSink rowsB = new StringSink();

    public QueryRunner(CairoEngine engine, SqlExecutionContext executionContext, boolean diffJit) {
        this.engine = engine;
        this.executionContext = executionContext;
        this.diffJit = diffJit;
    }

    public Result run(String sql) {
        if (!diffJit) {
            Outcome outcome = runOnce(sql, rowsA);
            return toResult(sql, outcome);
        }
        int prevJitMode = executionContext.getJitMode();
        try {
            executionContext.setJitMode(SqlJitMode.JIT_MODE_ENABLED);
            Outcome a = runOnce(sql, rowsA);
            executionContext.setJitMode(SqlJitMode.JIT_MODE_DISABLED);
            Outcome b = runOnce(sql, rowsB);
            return reconcile(sql, a, b, rowsA, rowsB);
        } finally {
            executionContext.setJitMode(prevJitMode);
        }
    }

    private static boolean isAcceptedSkip(Throwable t) {
        return t instanceof SqlException
                || t instanceof ImplicitCastException
                || t instanceof NumericException;
    }

    private static String renderOutcome(Outcome outcome, CharSequence rows) {
        if (outcome.failure == null) {
            return "ok, " + outcome.rowsRead + " rows:\n" + rows;
        }
        return outcome.exceptionClass + ": " + outcome.exceptionMessage;
    }

    private static Result toResult(String sql, Outcome outcome) {
        if (outcome.failure == null) {
            return Result.ok(outcome.rowsRead);
        }
        if (isAcceptedSkip(outcome.failure)) {
            return Result.skipped(outcome.exceptionClass + ": " + outcome.exceptionMessage);
        }
        return Result.failed(sql, outcome.failure);
    }

    private Outcome runOnce(String sql, StringSink rows) {
        rows.clear();
        try (RecordCursorFactory factory = engine.select(sql, executionContext)) {
            try (RecordCursor cursor = factory.getCursor(executionContext)) {
                RecordMetadata metadata = factory.getMetadata();
                int columnCount = metadata.getColumnCount();
                Record record = cursor.getRecord();
                int rowsRead = 0;
                while (cursor.hasNext()) {
                    for (int i = 0; i < columnCount; i++) {
                        CursorPrinter.printColumn(record, metadata, i, rows, false);
                        rows.put('\t');
                    }
                    rows.put('\n');
                    rowsRead++;
                }
                return Outcome.ok(rowsRead);
            }
        } catch (SqlException e) {
            return Outcome.error(e, e.getFlyweightMessage().toString());
        } catch (ImplicitCastException e) {
            return Outcome.error(e, e.getFlyweightMessage().toString());
        } catch (NumericException e) {
            return Outcome.error(e, "");
        } catch (Throwable t) {
            String msg = t.getMessage();
            return Outcome.error(t, msg == null ? "" : msg);
        }
    }

    private Result reconcile(String sql, Outcome a, Outcome b, StringSink rowsA, StringSink rowsB) {
        // Both succeeded.
        if (a.failure == null && b.failure == null) {
            if (Chars.equals(rowsA, rowsB)) {
                return Result.ok(a.rowsRead);
            }
            return Result.failed(sql, divergence(a, b, rowsA, rowsB));
        }
        // Both threw the same exception. Outcome the same way the single-run
        // path would: skip if allowlisted, fail if not.
        if (a.failure != null && b.failure != null
                && a.exceptionClass.equals(b.exceptionClass)
                && a.exceptionMessage.equals(b.exceptionMessage)) {
            if (isAcceptedSkip(a.failure)) {
                return Result.skipped(a.exceptionClass + ": " + a.exceptionMessage);
            }
            return Result.failed(sql, a.failure);
        }
        // Anything else: divergence (one succeeded, one threw; or both threw
        // different exceptions/messages).
        return Result.failed(sql, divergence(a, b, rowsA, rowsB));
    }

    private AssertionError divergence(Outcome a, Outcome b, CharSequence rowsA, CharSequence rowsB) {
        String msg = "JIT divergence:\n"
                + "  jit on : " + renderOutcome(a, rowsA) + "\n"
                + "  jit off: " + renderOutcome(b, rowsB);
        Throwable cause = a.failure != null ? a.failure : b.failure;
        return cause == null ? new AssertionError(msg) : new AssertionError(msg, cause);
    }

    private static final class Outcome {
        final String exceptionClass;
        final String exceptionMessage;
        final Throwable failure;
        final int rowsRead;

        private Outcome(int rowsRead, Throwable failure, String exceptionClass, String exceptionMessage) {
            this.rowsRead = rowsRead;
            this.failure = failure;
            this.exceptionClass = exceptionClass;
            this.exceptionMessage = exceptionMessage;
        }

        static Outcome error(Throwable t, String message) {
            return new Outcome(0, t, t.getClass().getSimpleName(), message);
        }

        static Outcome ok(int rowsRead) {
            return new Outcome(rowsRead, null, null, null);
        }
    }

    public static final class Result {
        private final Throwable failure;
        private final int rowsRead;
        private final String skipReason;
        private final String sql;
        private final State state;

        private Result(State state, int rowsRead, String skipReason, String sql, Throwable failure) {
            this.state = state;
            this.rowsRead = rowsRead;
            this.skipReason = skipReason;
            this.sql = sql;
            this.failure = failure;
        }

        public static Result failed(String sql, Throwable t) {
            return new Result(State.FAILED, 0, null, sql, t);
        }

        public static Result ok(int rowsRead) {
            return new Result(State.OK, rowsRead, null, null, null);
        }

        public static Result skipped(String reason) {
            return new Result(State.SKIPPED, 0, reason, null, null);
        }

        public Throwable getFailure() {
            return failure;
        }

        public int getRowsRead() {
            return rowsRead;
        }

        public String getSkipReason() {
            return skipReason;
        }

        public String getSql() {
            return sql;
        }

        public boolean isFailed() {
            return state == State.FAILED;
        }

        public boolean isSkipped() {
            return state == State.SKIPPED;
        }

        private enum State {OK, SKIPPED, FAILED}
    }
}
