/*******************************************************************************
 *     ___                  _   ____  ____
 *    / _ \ _   _  ___  ___| |_|  _ \| __ )
 *   | | | | | | |/ _ \/ __| __| | | |  _ \
 *   | |_| | |_| |  __/\__ \ |_| |_| | |_) |
 *    \__\_\\__,_|\___||___/\__|____/|____/
 *
 *  Copyright (c) 2014-2019 Appsicle
 *  Copyright (c) 2019-2022 QuestDB
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 ******************************************************************************/

package io.questdb.cutlass.line.tcp;

import org.jetbrains.annotations.NotNull;
import org.junit.Assert;
import org.junit.Test;

import java.net.URL;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

public class AuthDbTest {
    @Test
    public void testCryptoAlgorithm() throws Exception {
        // Generated by LineTcpReceiverTest.generateKeys
        // s: NgdiOWDoQNUP18WOnb1xkkEG5TzPYMda5SiUOvT1K0U=
        // testUser1	ec-p-256-sha256	Vs4e-cOLsVCntsMrZiAGAZtrkPXO00uoRLuA3d7gEcI=	ANhR2AZSs4ar9urE5AZrJqu469X0r7gZ1BBEdcrAuL_6

        PrivateKey privateKey = AuthDb.importPrivateKey("NgdiOWDoQNUP18WOnb1xkkEG5TzPYMda5SiUOvT1K0U=");
        PublicKey publicKey = AuthDb.importPublicKey("Vs4e-cOLsVCntsMrZiAGAZtrkPXO00uoRLuA3d7gEcI=", "ANhR2AZSs4ar9urE5AZrJqu469X0r7gZ1BBEdcrAuL_6");
        String challengeString = "XV54KEZwck9bNThoTlMpJnVNO216b2RAWlFneF1YVltYKi91PlItd1d7OEAuSVRQVysjQ09bMn4wSkVaWklcMlcoJHVwRGR7OiZzOUM2ZGkhdy9aKkEuPXJnPyQjMEtPQD1uVCBMLV4wWCs6ekx5NnwkdDF7dVxhO0goJy1uV2lhdSF2cjktWUlZVCA8M0EmWypCaFMhP0U7VFV5TyQgY2JWLyxJSkJvI1M8c0lUaXU6OzIlKVRGcEh4IVJHP0Bgdmkjfi42fVpTdiw8ZCo5Y3RhXFV0W2MwOm5Od0M4Tj0vWER3MGJiUEVBUlwyMS5RfEAvNWNwZnt7QzpReHN2SCdUZzR+MjYqeS51Lz5xXkVwXztUNyJtJE1NMCJcSDlZTSMzazxnUHksN3dGbFVsN15kPG5AUXNiSTY3Y20pXzFRXnhzZj5CM3EoI2dsVnpVZT41L25Se2wobChwSENHVkRxQyUlU3ExOUJIb3wgdGwweURoQnhkKlM7O0k1M2dwRU9Qe2NqaUwvey1wXFFJW08uWHIpM11PTFRETX1jK2JWU2MmJTBWZDk7YVZpI1A8THZaLykgVyFhe2x9O0xzICVGKGx3TD8tMz1bKUV+YUsmVyZvYXxiWTN5KT9DS2UlKVh+SFxUeTtXOnlidV0lejl6MFN9KH43Sn5+eEM3fXcK";
        byte[] challenge = challengeString.getBytes();
        Signature sig = Signature.getInstance(AuthDb.SIGNATURE_TYPE_DER);

        sig.initSign(privateKey);
        sig.update(challenge);
        byte[] sig2 = sig.sign();

        sig.initVerify(publicKey);
        sig.update(challenge);
        boolean verified = sig.verify(sig2);
        Assert.assertTrue(verified);
    }

    @Test
    public void testGetPublicKey_givenSinglePublicKeyConfigured_whenEmptyKeyIdRequested_thenReturnTheSingleKey() {
        LineTcpReceiverConfiguration configuration = configForAuthDB("authDb.txt");
        AuthDb authDb = new AuthDb(configuration);

        PublicKey publicKey = authDb.getPublicKey("");

        assertNotNull(publicKey);
    }

    @Test
    public void testGetPublicKey_givenMultiplePublicKeyConfigured_whenEmptyKeyIdRequested_thenReturnNull() {
        LineTcpReceiverConfiguration configuration = configForAuthDB("authDbWith2Keys.txt");
        AuthDb authDb = new AuthDb(configuration);

        PublicKey publicKey = authDb.getPublicKey("");

        assertNull(publicKey);
    }

    @Test
    public void testGetPublicKey_givenSinglePublicKeyConfigured_whenTheRightKeyIdRequested_thenReturnTheRightKey() {
        LineTcpReceiverConfiguration configuration = configForAuthDB("authDb.txt");
        AuthDb authDb = new AuthDb(configuration);

        PublicKey publicKey = authDb.getPublicKey("testUser1");

        assertNotNull(publicKey);
    }

    @Test
    public void testGetPublicKey_givenSinglePublicKeyConfigured_whenWrongKeyIdRequested_thenReturnNull() {
        LineTcpReceiverConfiguration configuration = configForAuthDB("authDb.txt");
        AuthDb authDb = new AuthDb(configuration);

        PublicKey publicKey = authDb.getPublicKey("notUser");

        assertNull(publicKey);
    }


    @NotNull
    private static LineTcpReceiverConfiguration configForAuthDB(String dbFile) {
        return new DefaultLineTcpReceiverConfiguration() {
            @Override
            public String getAuthDbPath() {
                URL u = getClass().getResource(dbFile);
                assert u != null;
                return u.getFile();
            }
        };
    }
}
