name: Build and Commit async-profiler Library
on:
  workflow_dispatch:
# This workflow is triggered manually from the Actions tab.
# It builds the async-profiler native library for Linux x86-64 from source
# and commits it to the current branch, providing a full audit trail.
#
# The async-profiler submodule is located at: core/src/main/c/share/async-profiler
# The built library will be placed at: core/src/main/bin/linux-x86-64/libasyncProfiler.so

jobs:
  build-async-profiler:
    runs-on: ubuntu-latest
    container:
      # We build inside the same container as async-profiler official builds
      # Source of the container: https://github.com/async-profiler/async-profiler/blob/07b3e747d167f8beb3ac961b87ff18ee40977ffb/docker/debian.Dockerfile
      image: public.ecr.aws/async-profiler/asprof-builder-x86@sha256:5244657fc3e9e3c5a0162d44777411c44031065071665776651068f94f7214f4
    steps:
      - name: Patch Debian buster repo and install dependencies
        run: |
          sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list
          apt-get update -y
          apt-get install git file -y

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Get async-profiler version info
        id: version
        run: |
          cd core/src/main/c/share/async-profiler
          ASYNC_VERSION=$(git describe --tags --always)
          ASYNC_SHA=$(git rev-parse --short=8 HEAD)
          echo "version=$ASYNC_VERSION" >> $GITHUB_OUTPUT
          echo "sha=$ASYNC_SHA" >> $GITHUB_OUTPUT
          echo "Building async-profiler version: $ASYNC_VERSION (commit: $ASYNC_SHA)"

      - name: Build async-profiler
        run: |
          cd core/src/main/c/share/async-profiler
          # Build using musl-gcc (same as official async-profiler releases)
          make CC=/usr/local/musl/bin/musl-gcc
          ls -la build/lib/libasyncProfiler.so
          echo "Library dependencies:"
          ldd build/lib/libasyncProfiler.so || true

      - name: Copy library to target location
        run: |
          mkdir -p core/src/main/bin/linux-x86-64/
          cp core/src/main/c/share/async-profiler/build/lib/libasyncProfiler.so core/src/main/bin/linux-x86-64/
          ls -la core/src/main/bin/linux-x86-64/libasyncProfiler.so
          file core/src/main/bin/linux-x86-64/libasyncProfiler.so
          ldd core/src/main/bin/linux-x86-64/libasyncProfiler.so || true

      - name: Commit and push changes
        run: |
          # Configure git and fix ownership issues
          git config --global --add safe.directory '*'
          git config --global user.name 'GitHub Actions - Build async-profiler'
          git config --global user.email 'jaromir@questdb.com'

          git add core/src/main/bin/linux-x86-64/libasyncProfiler.so

          # remove execute permission in Git index
          git update-index --chmod=-x core/src/main/bin/linux-x86-64/libasyncProfiler.so

          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          cat << EOF > commit_message.txt
          chore(build): rebuild async-profiler library for Linux x86-64 [skip ci]

          Built from async-profiler ${{ steps.version.outputs.version }} (commit: ${{ steps.version.outputs.sha }})
          Build timestamp: ${TIMESTAMP}
          GitHub Action: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          EOF

          git commit -F commit_message.txt

          # Push to current branch
          git push origin HEAD

          echo "Successfully committed and pushed async-profiler library update"

      - name: Summary
        if: always()
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ **async-profiler library rebuilt and committed successfully**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ steps.version.outputs.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **File**: \`core/src/main/bin/linux-x86-64/libasyncProfiler.so\`" >> $GITHUB_STEP_SUMMARY
