name: Build questdb.com on release

on:
  release:
    types: [published]

jobs:
  trigger-netlify-build:
    runs-on: ubuntu-latest

    steps:
      # Trigger website build
      - name: Trigger website build
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.WEBSITE_BUILD_HOOK_URL }}
        run: curl -X POST $NETLIFY_BUILD_HOOK_URL

      # Trigger docs build
      - name: Trigger docs build
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.DOCS_BUILD_HOOK_URL }}
        run: curl -X POST $NETLIFY_BUILD_HOOK_URL

      # Trigger release-notes build
      - name: Trigger release-notes build
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.RELEASE_NOTES_BUILD_HOOK_URL }}
        run: curl -X POST $NETLIFY_BUILD_HOOK_URL
