name: Build questdb.io on release

on:
  release:
    types: [published]

jobs:
  trigger-netlify-build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger build hook
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: curl -X POST $NETLIFY_BUILD_HOOK_URL
